### PR TITLE
erlang: Update to 27.1.3

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Release notes can be found [here](https://github.com/erlang/otp/releases/tag/OTP-27.1.3).

**Test Plan**
- Compiled an ran a hello world program.

**Checklist**

- [X] Package was built and tested against unstable
- [ ] This change could gainfully be listed in the weekly sync notes once merged (Write an appropriate message in the Summary section)

**Packaging notes**
- Seems to include static libraries. Needs double check.

### CODE REVIEW

**Comment by davidjharder** [comment]
It wouldn't be too hard to just delete these manually, but I don't know whether these are important to erlang somehow

```
pspec_x86_64.xml
128:            <Path fileType="library">/usr/lib64/erlang/erts-15.1.3/lib/internal/liberts_internal.a</Path>
129:            <Path fileType="library">/usr/lib64/erlang/erts-15.1.3/lib/internal/liberts_internal_r.a</Path>
130:            <Path fileType="library">/usr/lib64/erlang/erts-15.1.3/lib/internal/libethread.a</Path>
742:            <Path fileType="library">/usr/lib64/erlang/lib/erl_interface-5.5.2/lib/libei.a</Path>
743:            <Path fileType="library">/usr/lib64/erlang/lib/erl_interface-5.5.2/lib/libei_st.a</Path>
3572:            <Path fileType="library">/usr/lib64/erlang/usr/lib/libei.a</Path>
3573:            <Path fileType="library">/usr/lib64/erlang/usr/lib/libei_st.a</Path>
```

**Comment by androidnisse** [comment]
> It wouldn't be too hard to just delete these manually, but I don't know whether these are important to erlang somehow
> 
> ```
> pspec_x86_64.xml
> 128:            <Path fileType="library">/usr/lib64/erlang/erts-15.1.3/lib/internal/liberts_internal.a</Path>
> 129:            <Path fileType="library">/usr/lib64/erlang/erts-15.1.3/lib/internal/liberts_internal_r.a</Path>
> 130:            <Path fileType="library">/usr/lib64/erlang/erts-15.1.3/lib/internal/libethread.a</Path>
> 742:            <Path fileType="library">/usr/lib64/erlang/lib/erl_interface-5.5.2/lib/libei.a</Path>
> 743:            <Path fileType="library">/usr/lib64/erlang/lib/erl_interface-5.5.2/lib/libei_st.a</Path>
> 3572:            <Path fileType="library">/usr/lib64/erlang/usr/lib/libei.a</Path>
> 3573:            <Path fileType="library">/usr/lib64/erlang/usr/lib/libei_st.a</Path>
> ```

They were in the earlier package, so kinda seems they are needed.

**Comment by davidjharder** [comment]
@ianmjones you maintain an erlang tool for us, do you happen to know what these static libs are for?

**Comment by ianmjones** [comment]
Sorry, no idea I'm afraid, more of a budding Gleam user than Erlang.

**Comment by androidnisse** [comment]
@ermo @davidjharder 
I have removed the libraries and it still compiles the hello world program.

**Review by davidjharder — APPROVED** [review]
LGTM, thanks for your work

**Pull request merged**
