### PR TITLE
mullvad: Install icon

### PR DESCRIPTION
**Pull request by uni-dos**
**Summary**

- Update package to install the icon

**Test Plan**

- Logout of system and search for mullvad in app launcher

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by davidjharder — CHANGES_REQUESTED** [review]
Strictly speaking, this is not an NFC commit: the package has to be rebuilt to reflect the (small) change. Would you mind removing "NFC" from the commit message and PR description

**Comment by uni-dos** [comment]
Updated. I also just realized that I did not create a separate branch.

**Review by davidjharder — APPROVED** [review]
LGTM! Thanks for the fix.
You don't necessarily need a separate branch, but it would limit you to one PR at a time otherwise

**Comment by uni-dos** [comment]
Yeah I figured that out the hard way

**Pull request merged**
