### PR TITLE
Nvidia symlink safeguard

### PR DESCRIPTION
**Pull request by Staudey**
**Summary**

This adds a test to the end of the Nvidia driver package builds that checks for broken symlinks and stops the build if they are found, as suggested by @ReillyBrogan.

Ideas for improvements welcome.

**Test Plan**

Built a package with intentionally broken symlink and confirmed it was detected

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by Staudey** [comment]
To be rebased on https://github.com/getsolus/ypkg/pull/62

**Comment by davidjharder** [comment]
Hey @Staudey can this be closed now?

**Comment by Staudey** [comment]
Ye, I'm going to do this separately (for those that I haven't done it already).

**Comment by davidjharder** [comment]
Hey @Staudey, this branch can be nuked right?

**Comment by Staudey** [comment]
Oh. Yeah. Thanks, forgot that this was originally done when I was part of the team. Thought it was in my own repo ^^

**Pull request closed without merging**
