### PR TITLE
Update modem manager and dependencies

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Update modem-manager and dependencies
- This update fixes https://github.com/getsolus/packages/issues/1558

**Test Plan**
- Tested using a 4G-modem in both QMI and MBIM mode

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by androidnisse** [comment]
Marking as draft until someone can test this.

**Comment by malfisya** [comment]
As I already mention in matrix, I have the hardware. So far, after updating all packages (with your recipe) , the modem is still working. Is there any command you want me to test? Happy to oblige. Cheers !

**Comment by androidnisse** [comment]
> As I already mention in matrix, I have the hardware. So far, after updating all packages (with your recipe) , the modem is still working. Is there any command you want me to test? Happy to oblige. Cheers !

Thanks for testing, I think that should be enough so this is ready for review. :)

**Review by silkeh — APPROVED** [review]
Can confirm this works for a 4G modem using either MBIM or QMI. Thanks!

**Pull request merged**
