### PR TITLE
Update GHC to 9.4.8

### LINKED ISSUE #827: ghc 9.2.8 rel 11 FTBFS
### Summary

Our current version of `ghc` doesn't build

```
"inplace/bin/mkdirhier" utils/hsc2hs/dist/build/tmp//.
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Lib.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Ppr.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/PprLib.o
  HC [stage 0] libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Quote.o
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Ppr.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Lib.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/PprLib.o" does not exist (used with "-o" option.)
<command line>: error: directory portion of "libraries/template-haskell/dist-boot/build/Language/Haskell/TH/Quote.o" does not exist (used with "-o" option.)
libraries/hpc/ghc.mk:3: libraries/hpc/dist-boot/build/.depend-v.haskell: No such file or directory
```

### Steps to reproduce

Build GHC

### Expected result

Ghc to build

### Actual result

ghc doesn´t build

### Environment

- [X] Is system up to date?

### Repo

Unstable

### Desktop Environment

Other

### System details

N/A

### Other comments

_No response_

### PR DESCRIPTION
**Pull request by GZGavinZhao**
Fixes #827, #2165.

**Summary**

Update GHC (and the Haskell stack) to 9.4.8, the current recommended version of GHC in GHCup.

**Test Plan**

- Built `shellcheck` and `pandoc` using the updated `cabal-install`.
- `xmonad` ran successfully.

**Checklist**

- [x] Package was built and tested against unstable

**Changes**

- **ghc: Update to 9.4.8 and migrate to Hadrian**
- **haskell-base16-bytestring: Rebuild against GHC 9.4.8**
- **haskell-splitmix: Update to v0.1.0.5**
- **haskell-zlib: Rebuild against GHC 9.4.8**
- **haskell-th-compat: Rebuild against GHC 9.4.8**
- **haskell-tar: Rebuild against GHC 9.4.8**
- **haskell-network: Rebuild against GHC 9.4.8**
- **haskell-data-default-class: Rebuild against GHC 9.4.8**
- **haskell-setlocale: Rebuild against GHC 9.4.8**
- **haskell-lukko: Rebuild against GHC 9.4.8**
- **haskell-cryptohash-sha256: Rebuild against GHC 9.4.8**
- **haskell-base64-bytestring: Rebuild against GHC 9.4.8**
- **haskell-ed25519: Rebuild against GHC 9.4.8**
- **haskell-data-array-byte: Deprecate**
- **haskell-cabal-syntax: Update to v3.8.1.0**
- **haskell-regex-base: Rebuild against GHC 9.4.8**
- **haskell-echo: Rebuild against GHC 9.4.8**
- **haskell-utf8-string: Rebuild against GHC 9.4.8**
- **haskell-resolv: Update to v0.2.0.2**
- **haskell-random: Rebuild against GHC 9.4.8**
- **haskell-network-uri: Rebuild against GHC 9.4.8**
- **haskell-hashable: Update to v1.4.3.0**
- **haskell-x11: Rebuild against GHC 9.4.8**
- **haskell-regex-posix: Rebuild against GHC 9.4.8**
- **haskell-edit-distance: Rebuild against GHC 9.4.8**
- **haskell-http: Rebuild against GHC 9.4.8**
- **haskell-hackage-security: Rebuild against GHC 9.4.8**
- **xmonad: Rebuild against GHC 9.4.8**
- **haskell-x11-xft: Rebuild against GHC 9.4.8**
- **haskell-async: Update to v2.2.5**
- **haskell-cabal-install-solver: Add at v3.8.1.0**
- **xmonad-contrib: Rebuild against GHC 9.4.8**
- **haskell-safe-exceptions: Add at  v0.1.7.4**
- **haskell-cabal-install: Update to v3.8.1.0**
- **pandoc: Rebuild against GHC 9.4.8**
- **shellcheck: Rebuild against GHC 9.4.8**
- **pandoc-crossref: Rebuild against GHC 9.4.8**

### CODE REVIEW

**Comment by davidjharder** [comment]
How do you want to handle `homepage` for the packages missing them?
We could let the homepage adding contributors loose on Haskell packages after this is merged. My opinion: homepage should use the `haskell.hackage` page.

**Comment by malfisya** [comment]
Changes : 
- Rebase the commits
- Rebuild all packages against latest revision
- Added homepage(s)
- Add monitoring.yml(s)
- Deprecate `haskell-data-array-byte` properly
- Fix minor capitalization and wording mistakes in commit message

**Review by HarveyDevel — CHANGES_REQUESTED** [review]
From the pspec's it appears these packages will no longer exist and should be deprecated:

```
ghc-devel
haskell-async-devel
haskell-base16-bytestring-devel
haskell-base64-bytestring-devel
haskell-cryptohash-sha256-devel
haskell-data-default-class-devel
haskell-echo-devel
haskell-ed25519-devel
haskell-edit-distance-devel
haskell-hackage-security-devel
haskell-hashable-devel
haskell-lukko-devel
haskell-network-uri-devel
haskell-network-devel
haskell-random-devel
haskell-regex-base-devel
haskell-regex-posix-devel
haskell-resolv-devel
haskell-setlocale-devel
haskell-splitmix-devel
haskell-tar-devel
haskell-th-compat-devel
haskell-utf8-string-devel
haskell-x11-xft-devel
haskell-x11-devel
haskell-zlib-devel
```

**Review by HarveyDevel — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
