### PR TITLE
update knotes

### PR DESCRIPTION
**Pull request by BoatyPillow**
- **knotes:**
- **knotes:Updated summary & description**

**Summary**

Fixes getsolus/packages#3606

**Test Plan**

Tested on KDE Plasma, could write and save notes while "sticking" to desktop
**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by TraceyC77 — CHANGES_REQUESTED** [review]
The code looks good, but this PR has two commits. Our tooling expects all PRs to have only one commit. You'll need to squash the two commits, then this will be ready for merge. Thanks!

**Comment by BoatyPillow** [comment]
> The code looks good, but this PR has two commits. Our tooling expects all PRs to have only one commit. You'll need to squash the two commits, then this will be ready for merge. Thanks!

Took care of the commit issue!

**Review by TraceyC77 — APPROVED** [review]

**Review by TraceyC77 — CHANGES_REQUESTED** [review]
OK, now that you have one commit, you need to update the summary and description in this PR via the web to match the expected format. The commit has the right summary, just copy and paste that into this PR's summary. This PR's description just needs a little cleanup (it has a duplicate line).

**Comment by ReillyBrogan** [comment]
It appears that the summary and description was changed in the pspec but not the package.yml

**Comment by ReillyBrogan** [comment]
See getsolus/packages#3813. This is being removed from the repo instead.

**Pull request closed without merging**
