### PR TITLE
lmms: add appstream data

### PR DESCRIPTION
**Pull request by uni-dos**
**Summary**
- add appstream data (adapted from flathub lmms)

**Test Plan**

ensure appstream data is install.

**Checklist**

- [x] Package was built and tested against unstable

Resolves https://github.com/getsolus/packages/issues/3381

### CODE REVIEW

**Review by malfisya — CHANGES_REQUESTED** [review]
Did you already verify the appstream metainfo with `appstream-builder --packages-dir=. --include-failed -v` ? https://github.com/getsolus/solus-appstream-data?tab=readme-ov-file#testing-individual-packages

**Comment by uni-dos** [comment]
In the `example-failed.xml.gz` it has a veto for icon and in `examplexml.gz` it is not generated.

**Comment by uni-dos** [comment]
I am not sure if I did it correctly. I had to rename the .desktop entry from lmms.desktop to io.lmms.LMMS.desktop.

**Comment by uni-dos** [comment]
I get 2 tag-missing and a style-invalid fail.

**Comment by malfisya** [comment]
> I get 2 tag-missing and a style-invalid fail.

Where did you get this warning? If it is from `appstreamcli validate` you can ignore it.

> I am not sure if I did it correctly. I had to rename the .desktop entry from lmms.desktop to io.lmms.LMMS.desktop.

So, you have two options: 1. Do what you did; 2. Add new key in the appstream metainfo
```
<launchable type="desktop-id">DESTKTOPFILENAME.desktop</launchable>
```
This key ensure the parser to parse the right desktop file even the desktop file doesn't use the APPID format. I prefer this solution.

**Review by malfisya — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
