### PR TITLE
snippetexpander: Add at v1.0.3

### PR DESCRIPTION
**Pull request by ianmjones**
**Summary**

Add the snippetexpander package, your little expandable text snippet helper.

Resolves getsolus/packages#3636

**Test Plan**

* Build and install package locally.
* Test main window, adding snippets etc.
* Test search and paste window.
* Test auto expand functionality in compatible app (e.g. LibreOffice Writer)
* Test CLI.
* I've been using it for months now! (also, I'm the developer)

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by EbonJaeger — DISMISSED** [review]
When specifying build dependencies, it is preferred to use `pkgconfig` names whenever possible. So, for `wtype`, for example, the list should look like this:

```yaml
builddeps  :
    - pkgconfig(wayland-client)
    - pkgconfig(xkbcommon)
```

Also note that our packages have somewhat automatic dependency resolution; if a binary in a package links against another binary, the package containing it is automatically added as a runtime dependency. So, you probably don't need to specify `libwebkit-gtk` as long as it is linked to during the build.

All dependencies should also be sorted alphabetically. :)

**Comment by ianmjones** [comment]
Thanks for the review @EbonJaeger, and the great advice!

I think I've resolved everything you mentioned, and I have rebuilt and tested locally.

**Comment by ianmjones** [comment]
Just noticed the warning on my latest commits that the `builddeps` in `snippetexpander/package.yml` are not in the correct order, because apparently the `pkgconfig()` entries should be before the rest of the dependencies, and so not strictly in alphabetical order.

I'll fix that up.

**Comment by ianmjones** [comment]
OK, think we're all good now. :tada:

**Review by davidjharder — APPROVED** [review]
LGTM!

**Pull request merged**
