### PR TITLE
keybase: Set correct permission for run_keybase

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Resolves getsolus/packages#2177
- Add monitoring.yml

**Test Plan**

Launch the app succsesfully from terminal and desktop

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by malfisya** [comment]
Honestly, not sure if this is the correct fix. I tried to just rebuild the app locally (without the fix) and it just launched fine. Permission was set correctly. But the repo package got wrong permission.

**Comment by davidjharder** [comment]
I'm baffled. The terminal start reported in the issue works fine for me, and pspec lists the file as an executable:
https://github.com/getsolus/packages/blob/1212592fb8b64138e121aed2ab84a21d10e401c3/packages/k/keybase/pspec_x86_64.xml#L29

@malfisya were you able to reproduce the error?

**Comment by malfisya** [comment]
It is weird. Not sure when the permission change. I am not using keybase regularly to track it down. :shrug:

**Review by davidjharder — APPROVED** [review]
This fix works. Waiting for build server availability before merging

**Pull request merged**
