### PR TITLE
lua51 : Add homepage

### PR DESCRIPTION
**Pull request by uni-dos**
**lua51: add homepage**

**Summary**

Add homepage to lua 5.1

**Test Plan**

Ensure package builds

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by malfisya — CHANGES_REQUESTED** [review]
Commit and PR message doesn't follow standard formatting.

```
package : changes
```

**Comment by uni-dos** [comment]
My bad. I don't think my brain was working when I submitted this.

**Comment by malfisya** [comment]
The commit message haven't been edited :confused: .

**Review by malfisya — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
