### PR TITLE
nuget: Update to 6.0.0.280

### PR DESCRIPTION
**Pull request by nelsontkq**
**Summary**

Updated to a version with a working nuget build repository.

new features: Source mapping, .net 6 support, warns about package vulnerabilities.

Full release notes available [here](https://devblogs.microsoft.com/nuget/announcing-nuget-6/)

Solves #2635 

**Test Plan**

 - Pack a .net class project
 - install a nuget package
 - confirm godot builds with new nuget version

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by davidjharder — APPROVED** [review]
Thanks. We appreciate your work on this ecosystem.

**Comment by davidjharder** [comment]
@nelsontkq this fails when applying `remove-ilmerge.patch`

**Comment by nelsontkq** [comment]
@davidjharder looks like the carriage return was removed from the line endings in the patch file on commit. I'll put up another PR

**Comment by nelsontkq** [comment]
@davidjharder [Here it is](https://github.com/getsolus/packages/pull/2801)

**Pull request merged**
