### PR TITLE
shotcut: Update to 22.12.21

### LINKED ISSUE #187: Update shotcut to 22.06.23 (T10344)
<div dir="rtl"><b>Xon</b>&nbsp;(<em>&#35;xonus</em>),&nbsp;2022-08-18&nbsp;05:25:12&nbsp;UTC</div><br/>

fixing some bugs (theme bug, unexpected crashes), adding new functionality
link to source: https://www.shotcut.org/download/

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Changelog(s):
   - [22.12.21](https://github.com/mltframework/shotcut/releases/tag/v22.12.21) 
   - [22.11.25](https://github.com/mltframework/shotcut/releases/tag/v22.11.25) 
   - [22.10.25](https://github.com/mltframework/shotcut/releases/tag/v22.10.25) 
   - [22.10.22](https://github.com/mltframework/shotcut/releases/tag/v22.12.21) 
   - [22.09.23](https://github.com/mltframework/shotcut/releases/tag/v22.09.23) 
   - [22.06.03](https://github.com/mltframework/shotcut/releases/tag/v22.06.03) 
   - [22.04.25](https://github.com/mltframework/shotcut/releases/tag/v22.04.25)
   - [22.03.30](https://github.com/mltframework/shotcut/releases/tag/v22.03.30)
   - [21.12.24](https://github.com/mltframework/shotcut/releases/tag/v21.12.24)
   - [21.12.21](https://github.com/mltframework/shotcut/releases/tag/v21.12.21)
- Resolves #187

**Test Plan**

- Open project files
- Render test video

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by algent-al** [comment]
The diff is fine. Can you please delete also the `MAINTAINER.md`file, since the maintainer there isn't using Solus anymore.

**Comment by malfisya** [comment]
Ah, sure

**Comment by algent-al** [comment]
> Should i add back `%qml_cache` to install step? It precompiles `.qml` files to `.qmlc`, so i thought it might the app startup faster. It didn't.

Yes, add it back please!

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
