### PR TITLE
gnome-multi-writer: include homepage

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Add homepage to package.yml

**Test Plan**

- Checked homepage was added

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by algent-al — CHANGES_REQUESTED** [review]
Marking this as Request changes, since this PR conflicts with https://github.com/getsolus/packages/pull/1950/commits stack by @joebonrichie.

**Comment by androidnisse** [comment]
> Marking this as Request changes, since this PR conflicts with https://github.com/getsolus/packages/pull/1950/commits stack by @joebonrichie.

Yes you are correct, I will let him deal with the Gnome applications. :)

**Review by algent-al — CHANGES_REQUESTED** [review]
Please resolve builddeps order as reported from `GitHub Actions / Checks`.

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
