### PR TITLE
 arm-none-eabi-gcc: Update to 13.2.0

### PR DESCRIPTION
**Pull request by malfisya**
**Test Plan**

- Built firmware for arm device, used this [keyboard](https://github.com/tmk/tmk_keyboard/tree/master/keyboard/infinity)

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by silkeh** [comment]
@malfisya: Thanks for taking the time to update this package. Next time please request a package update when there is a maintainer for a package (see [MAINTAINERS.md](https://github.com/getsolus/packages/blob/main/packages/a/arm-none-eabi-gcc/MAINTAINERS.md)).

@chax: mind giving this a review?

**Comment by malfisya** [comment]
Sorry about that

**Comment by TraceyC77** [comment]
@chax , are you available to review this pull request? It's been waiting for a while. If you're not in a position to maintain packages anymore, please let us know so we can request another maintainer. If you've just been busy that's understandable, just let us know.

**Review by chax — APPROVED** [review]
I think this is good to go, and yes, I've been busy with private things lately.
LGTM

**Review by TraceyC77 — APPROVED** [review]
@chax approved the change. Thanks!

**Comment by TraceyC77** [comment]
@malfisya please squash your commits, and then this is ready to be merged.

**Comment by malfisya** [comment]
> please squash your commits, 

When you say "squash", does it means rebase? This one : `git rebase -i origin/main`. Just wanna make sure.

**Comment by chax** [comment]
i guess this one is good to go, can be merged

> > please squash your commits,
> 
> When you say "squash", does it means rebase? This one : `git rebase -i origin/main`. Just wanna make sure.

To "squash" commits, use `git rebase -i HEAD~3` (HEAD~3 means use last 3 commits, -i means interactively), and then it will open editor for you, and you need to change "pick pick pick" into "pick squash squash", or just "pick s s" for short version.
Then you save changes in that editor and exit, and squashing will begin, after which it will ask you for new commit message for those three commits combined. Edit the message and again, save and exit. This will rebase branch to have only one commit containing all the changes. Then you just force-push into your remote branch and that's it.

**Comment by silkeh** [comment]
This PR does not need to be squashed as every commit updates a separate package (which is the right way to do it afaik).

**Comment by chax** [comment]
> This PR does not need to be squashed as every commit updates a separate package (which is the right way to do it afaik).

Yeah, i think so too.

**Pull request merged**
