### PR TITLE
libunibreak: Add homepage

### PR DESCRIPTION
**Pull request by A108384**
**Summary**
- Add homepage to package.yml
**Test Plan**
- Successfully build and install new package
- Successfully execute and split text using[ breaktext](https://github.com/adah1972/breaktext) utility

**Checklist**
- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by EbonJaeger — CHANGES_REQUESTED** [review]
This has a .so version bump, so packages that depend on this will have to be rebuilt as a part of the Pull Request:

- naev
- libass
- krita
- fbreader

**Comment by A108384** [comment]
Hello.  There are a couple problems with the follow-up rebuilds.  

fbreader is no longer open-source and even the original source for the build is no longer available.
krita does not build (even without the library update).  This build is very long and complex-ish, so I would rather tackle it another day.  
There were no problems with naev or libass.  
So I am going to reverse the libunibreak update  from 5.1 to 6.1 and just focus on the homepage.  
I'll open a couple of issues on the issues with Krita & fbreader.

**Comment by A108384** [comment]
I re-based this, then rebuilt with only the homepage update, keeping the version at 5.1  This makes is much simpler and avoids the dependency rebuild complexity.

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
