### PR TITLE
clj-kondo: Update to 2024.03.05

### PR DESCRIPTION
**Pull request by olymk2**
**Summary**

- Changelog can be found [here](https://github.com/clj-kondo/clj-kondo/blob/v2024.03.05/CHANGELOG.md)

**Test Plan**

- Installed locally and ran clj-kondo --version to check updated version returned

**Checklist**

- [ ] Package was built and tested against unstable

### CODE REVIEW

**Review by davidjharder — CHANGES_REQUESTED** [review]
Please remove the indentation in front of the bullet points for *summary* and *test plan*, in the commit message and the PR description.

Also, I assume you tested on unstable, so check the box at the bottom of the PR description.

Other than that, looks good.

**Comment by olymk2** [comment]
> Please remove the indentation in front of the bullet points for _summary_ and _test plan_, in the commit message and the PR description.
> 
> Also, I assume you tested on unstable, so check the box at the bottom of the PR description.
> 
> Other than that, looks good.

I do not usually test on unstable, I build locally and install and just try using it on my machine, not sure how I would even test on unstable VM or something ? 

I will remove the indentation.

**Comment by davidjharder** [comment]
I'm assuming you're using the unstable repository on your local machine since you are packaging.
Testing locally is perfectly fine, it's what we want.

Or am I not understanding something about your setup?

**Comment by davidjharder** [comment]
To be super clear:

- When we say "built on unstable" we mean using the unstable profile in solbuild, as you just showed.
- And "tested on unstable" just means installed and working on a machine running the unstable repo: `eopkg lr` returns `https://cdn.getsol.us/repo/unstable/eopkg-index.xml.xz`

So your testing is fine and you can check the box.

**Comment by olymk2** [comment]
@davidjharder So i ran your command I get https://cdn.getsol.us/repo/shannon/eopkg-index.xml.xz so probably not what your after, I would rather avoid switching to unstable packages as this is a work machine which I don't want to hit issues with.

In the past when I have submitted packages I have not checked this and its been fine, is this a new requirement or is it not a hard requirement ?

**Comment by davidjharder** [comment]
This is not a new requirement, maybe I just assumed. And we know what happens when you assume.

In theory, building as unstable and testing locally with stable (shannon) should be fine except you would occasionally run into errors with dependencies that you would not otherwise. We recommend a "unified" environment to avoid these dependency bugs.

Please consider setting up a VM for quick unstable testing.

I'll accept this package and nushell with your current testing setup

**Review by davidjharder — APPROVED** [review]

**Comment by olymk2** [comment]
okay great thanks I think most of the packages I change are quite contained, but I will see about setting up a vm for the future.

**Comment by davidjharder** [comment]
Yeah, this one is a perfect example of it. You would only see errors if we had big changes to `glibc` or `libz` in unstable

**Pull request merged**
