### PR TITLE
pycups: update to 2.0.1

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Release notes can be found [here](https://github.com/OpenPrinting/pycups/blob/master/NEWS).
- Inclusion of "homepage" to package.yml
- Part of https://github.com/getsolus/packages/issues/411

**Test plan**
- Built system-config-printer against this.

**Check list**
- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by EbonJaeger** [comment]
Does `system-config-printer` actually need to be rebuilt, or will it still work without a rebuild?

**Comment by androidnisse** [comment]
> Does `system-config-printer` actually need to be rebuilt, or will it still work without a rebuild?

I just chose a package was dependent on this to see that it still built.

**Comment by EbonJaeger** [comment]
The tricky thing with Python packages is that there is no compile-time linking; it either works at run time or it explodes.

**Comment by androidnisse** [comment]
> The tricky thing with Python packages is that there is no compile-time linking; it either works at run time or it explodes.

So how would one safely test this update?

**Comment by EbonJaeger** [comment]
I would try to test our current `system-config-printer` with the updated `pycups` installed. It's a graphical application, so it should be pretty obvious if it doesn't work. (Famous last words)

**Comment by androidnisse** [comment]
> I would try to test our current `system-config-printer` with the updated `pycups` installed. It's a graphical application, so it should be pretty obvious if it doesn't work. (Famous last words)

It started with the new version and nothing exploded, so seems to work.

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks! :)

**Pull request merged**
