### PR TITLE
hatari: Update to 2.41

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Full release note can be found [here](https://hatari.tuxfamily.org/news.html)
- Add appstream metainfo (Part of getsolus/packages#1389)

**Test Plan**

- Verify metadata with `appstream-builder --packages-dir=. --include-failed -v`

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by malfisya** [comment]
For some reason `hatariui` isn't build. It says python 3 is required, but it is already on builddeps. I saw [fedora](https://src.fedoraproject.org/rpms/hatari/blob/rawhide/f/hatari.spec) and [opensuse](https://build.opensuse.org/package/view_file/Emulators/hatari/hatari.spec?expand=1) recipes, they patch a few python files to uses their macro. I tried to do that too (specifically fedora with `sed` but to `/usr/bin/python3`), but it didn't work. Also tried using `export PYTHONPATH=$PYTHONPATH:/usr/bin/python3` on setup process, didn't work. There must be something obvious i missed. Any advice please?

**Comment by Staudey** [comment]
This patch should do the trick:

```
From 5a8111f93818dc9a5b9b2134bb41c546d2d85c1a Mon Sep 17 00:00:00 2001
From: Thomas Staudinger <Staudi.Kaos@gmail.com>
Date: Sun, 4 Feb 2024 12:50:33 +0100
Subject: [PATCH] CMakeList.txt: Use FindPython3

Signed-off-by: Thomas Staudinger <Staudi.Kaos@gmail.com>
---
 CMakeLists.txt | 12 ++++--------
 1 file changed, 4 insertions(+), 8 deletions(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index c58c29d0..b23d4830 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -370,14 +370,10 @@ if(NOT CMAKE_CROSSCOMPILING)
 	add_subdirectory(tests)
 endif(NOT CMAKE_CROSSCOMPILING)
 
-include(FindPythonInterp)
-if(PYTHONINTERP_FOUND AND PYTHON_VERSION_MAJOR LESS 3)
-	message("Note: Hatari needs at least Python 3 ... ignoring older version")
-	unset(PYTHONINTERP_FOUND)
-endif()
+include(FindPython3)
 set(PYTHON_GTK_FOUND 0)
-if(PYTHONINTERP_FOUND)
-	execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "\
+if(Python3_Interpreter_FOUND)
+	execute_process(COMMAND ${Python3_EXECUTABLE} -c "\
 import gi\n\
 gi.require_version('Gtk', '3.0')\n\
 from gi.repository import Gtk\n\
@@ -390,7 +386,7 @@ from gi.repository import GLib"
 		set(PYTHON_GTK_FOUND 1)
 		add_subdirectory(python-ui)
 	endif()
-endif(PYTHONINTERP_FOUND)
+endif(Python3_Interpreter_FOUND)
 
 if(UNIX AND NOT ENABLE_OSX_BUNDLE)
 	add_subdirectory(share)
-- 
2.43.0
```

**Comment by malfisya** [comment]
Thank you @Staudey !

**Review by davidjharder — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
