### PR TITLE
mouse-actions-gui: Add at v0.4.5

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Resolves https://github.com/getsolus/packages/issues/3993

**Test Plan**
- Installed loaded and tried some gestures.
- The Mouse Actions GUI has been introduced as a replacement for Easystroke, offering an updated and streamlined interface for configuring mouse gestures and actions.

**Checklist**

- [ ] Package was built and tested against unstable
- [X] This change could gainfully be listed in the weekly sync notes once merged

### CODE REVIEW

**Review by EbonJaeger — CHANGES_REQUESTED** [review]
I added a project page for this [here](https://release-monitoring.org/project/376063/), if you wouldn't mind adding a `monitoring.yml` :)

**Comment by EbonJaeger** [comment]
Also, now needs to be rebased because of the deprecation. Sorry.

**Comment by EbonJaeger** [comment]
I think something went wrong with the commits here; there's only one, and it includes my gtkhash work.

**Comment by androidnisse** [comment]
> I think something went wrong with the commits here; there's only one, and it includes my gtkhash work.

Rebase broke this.

**Pull request closed without merging**
