### PR TITLE
common/Scripts: add check_update function to helper.sh

### PR DESCRIPTION
**Pull request by joebonrichie**
**Summary**
- for quick anitya monitoring of a single package

**Test Plan**

source script in environment and run check_update on a bunch of packages

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by davidjharder** [comment]
How much of a pain is it to write fish and zsh versions?

Seems there is no good way to call a bash *function* from within the fish shell

**Comment by silkeh** [comment]
> How much of a pain is it to write fish and zsh versions?
> Seems there is no good way to call a bash function from within the fish shell

I'd make it a separate script instead and call that from all three helper functions.

**Comment by ermo** [comment]
@joebonrichie Have you any appetite for making this into a standalone script and then calling said script from each of the helper scripts...?

**Review by ermo — CHANGES_REQUESTED** [review]
The code in itself is sound.

However, it would be _way_ more useful if the actual logic was made into a standalone script, which is then called from the various helper scripts via a function.

Do you have any appetite for doing this rewrite?

**Comment by malfisya** [comment]
With `ent` landing in repository, wouldn't that supersede this PR?

**Comment by ermo** [comment]
> With `ent` landing in repository, wouldn't that supersede this PR?

Only once `ent` begins supporting checking for updates per package?

**Comment by malfisya** [comment]
> Only once `ent` begins supporting checking for updates per package?

`ent` can check per package (provided it has monitoring.yml, of course).  Just navigate to a package directory, say `systemd`:
```
░▒▓    …/packages/s/systemd   main  󰥔 19:52                                                                                                                      
❯ go-task updatecheck                                                                                                                                                   
task: [updatecheck] ent check updates                                                                                                                                   
Checking for updates...                                                                                                                                                 
                                                                                                                                                                        
Total packages to update: 1                                                                                                                                             
                                                                                                                                                                        
Package Current Latest                                                                                                                                                  
------- ------ ---                                                                                                                                                      
systemd 254.21 257                                                                                                                                                      
                                                                                                                                                                        
░▒▓    …/packages/s/systemd   main  󰥔 19:52                                                                                                                      
❯ ent check updates                                                                                                                                                     
Checking for updates...                                                                                                                                                 
                                                                                                                                                                        
Total packages to update: 1                                                                                                                                             
                                                                                                                                                                        
Package Current Latest                                                                                                                                                  
------- ------ ---                                                                                                                                                      
systemd 254.21 257                                                                                                                                                      
                                                                                                                                                                        
░▒▓    …/packages/s/systemd   main  󰥔 19:52                                                                                                                      
❯ 
```

**Comment by ermo** [comment]
Closing as this functionality is superseded by Serpent's `ent` tool.

Thank you nonetheless @joebonrichie ! :muscle:

**Pull request closed without merging**
