### PR TITLE
papirus-icon-theme: update to 20230901

### PR DESCRIPTION
**Pull request by Staudey**
**Summary**

Release notes available [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/releases/tag/20230901)

**Test Plan**
Checked icons in application menu, file explorer, and SC

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
> Use `fatfakeroot` to fix issues with the build

What exactly does it fix? Does the build fail without it?

**Comment by Staudey** [comment]
Yes, build fails without it, with errors like:

```
install -Dm00644 /home/build/YPKG/root/papirus-icon-theme/install//usr/share/icons/Papirus/32x32/apps//android-studio.svg /home/build/YPKG/root/papirus-icon-theme/install/usr/share/icons/solus-sc/32x32/apps/android-studio.svg
install: cannot change permissions of '/home/build/YPKG/root/papirus-icon-theme/install/usr/share/icons/solus-sc/32x32/apps/android-studio.svg': No such file or directory
```

After realizing that the setup step (which should be the only one affected by `fatfakeroot`) is tiny, I tried some more things.
Apparently this is connected to the` rm -r ePapirus*` somehow. When I move it to the `install` section, which has fat fakeroot by default, it works fine. Not sure what is going on here.

**Review by ReillyBrogan — APPROVED** [review]
LGTM

**Review by ReillyBrogan — CHANGES_REQUESTED** [review]
Actually no, can you squash these commits?

**Comment by Staudey** [comment]
Done!

**Review by ReillyBrogan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
