### PR TITLE
fb2converter: Update to 1.75.1

### PR DESCRIPTION
**Pull request by nazar-stasiv**
**Summary**
- Added "#series_first_word" to "title_format" and "file_name_format" configuration options.
- There is also "series_first_word_length" (default is set to 4) to set cut off length

**Test Plan**
- fb2c convert infile

**Checklist**
- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by davidjharder — APPROVED** [review]
Thanks!

**Comment by algent-al** [comment]
This package failed to build in build-server.

**Comment by nazar-stasiv** [comment]
> This package failed to build in build-server.

I looked into build server log file, there's not much info besides there was an error.

**Comment by EbonJaeger** [comment]
Whatever `task: Command "tput setaf 4" failed: exit status 1` does, didn't. It does build fine locally for me.

**Pull request merged**
