### PR TITLE
font-iosevka-ttf: Update to 27.3.5

### PR DESCRIPTION
**Pull request by nazar-stasiv**
**Summary**
- Add italic form of CYRILLIC SMALL LETTER THREE-LEGGED TE
- Add top-right serif to fully serifed form for CYRILLIC SMALL LETTER TALL TE
- Fix serifs of GREEK LETTER DIGAMMA (U+03DC) under ss12.
- Improve crossbar position of GREEK SMALL LETTER DIGAMMA (U+03DD) and add a middle serif under slab.
- Refine Greek Capital Sho (U+03F7) glyph
- Make SYMBOL FOR DELETE FORM TWO (U+2425) narrow by default, align with other Control Pictures characters
- Make APL FUNCTIONAL SYMBOL CIRCLE STAR (U+235F) always be five-pointed and upright, to align its pentagram history

**Test Plan**
- render text with the font

**Checklist**
- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by algent-al** [comment]
Hi @nazar-stasiv. Is there any reason why you marked this PR as draft?

**Comment by nazar-stasiv** [comment]
> Hi @nazar-stasiv. Is there any reason why you marked this PR as draft?

To make sure it passes checks.

**Comment by silkeh** [comment]
@nazar-stasiv: the PR being draft or not should not matter for the checks. Or do you mean that you submit the PR and wait for the checks to pass before marking it as ready?

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
