### PR TITLE
xfce 4.20

### PR DESCRIPTION
**Pull request by EbonJaeger**
**Summary**

Update the XFCE stack to 4.20.

- **xfce4-dev-tools: Update to v4.19.4**
- **libxfce4util: Update to v4.19.4**
- **xfconf: Update to v4.19.4**
- **libxfce4ui: Update to v4.19.6**
- **garcon: Update to v4.19.2**
- **exo: Update to v4.19.1**
- **libxfce4windowing: Update to v4.19.9**
- **xfce4-panel: Update to v4.19.6**
- **thunar: Update to v4.19.4**
- **thunar-volman: Update to v4.19.0**
- **xfce4-appfinder: Update to v4.19.3**
- **xfce4-power-manager: Update to v4.19.4**
- **xfce4-session: Update to v4.19.3**
- **xfce4-settings: Update to v4.19.3**
- **tumbler: Update to v4.19.2**
- **xfdesktop: Update to v4.19.6**
- **xfwm4: Update to v4.19.0**
- **xfce4-notifyd: Build with Wayland support**
- **xfce4-desktop-branding: Drop xfdesktop config**
- **xfce4-pulseaudio-plugin: Update to v0.4.9**

**Test Plan**

Update all packages and restart, use as a daily driver for a month and a half. Create a new user and ensure that defaults are set correctly.

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by minhhut** [comment]
I have followed the guide and switched to testing repo. The first thing I have tried is that login to Wayland kick me out right away. Please give a guideline how I could collect the logs or give more details here. 
image

**Comment by EbonJaeger** [comment]
You will need a Wayland compositor installed. By default, it looks like XFCE4 looks for labwc. Do keep in mind that Wayland support in XFCE is currently experimental at best, and may not be supported yet.

**Comment by EbonJaeger** [comment]
It looks like several components crash when you try to do this. Please do not try the Wayland session yet.

**Comment by EbonJaeger** [comment]
Moved the Wayland session into a separate package: `xfce4-session-wayland`

**Comment by EbonJaeger** [comment]
The following changes have been made to the `xfdesktop` package:

- Set default background via build script
- Disable desktop menu module (it wasn't shown by default due to our branding, anyway)

You will have to reinstall the package if you're testing the 4.20pre1 updates.

**Comment by Ernesto2660** [comment]
Hi
24 hours ago, I installed XFCE 4.20 on an external SSD. I installed XFCE 4.20 in the same configuration as the 4.18 I usually use, except for the icons and theme.
Observation on XFCE itself: multiplication of tabs on the Desktop settings menu.
Impossible to close the computer via the whisker menu to restart the system once the installation is complete. 
In terms of software, GIMP freezes on the foreground extraction tool, having first used the 3D transformation tool to enlarge the photo. As a result, it is impossible to switch off the computer via the whisker menu, which is no longer accessible. The top panel containing the windows button is no longer efficient.
For the moment, with the exception of these 3 points, it's perfect.
Thanks to the team for all their hard work.

Translated with DeepL.com (free version)

**Comment by EbonJaeger** [comment]
> Observation on XFCE itself: multiplication of tabs on the Desktop settings menu.

I am unsure what this means, or where to look. Can you post a screenshot?

> Impossible to close the computer via the whisker menu to restart the system once the installation is complete.

Probably because the library to do that moved out from under the running system; that is why we want offline update support.

> In terms of software, GIMP freezes on the foreground extraction tool, having first used the 3D transformation tool to enlarge the photo. As a result, it is impossible to switch off the computer via the whisker menu, which is no longer accessible. The top panel containing the windows button is no longer efficient.

This sounds more like a GIMP bug than anything to do with XFCE.

**Comment by Ernesto2660** [comment]
Capture d’écran_2024-11-09_18-30-22

**Comment by Ernesto2660** [comment]
I hope it will ok

**Comment by EbonJaeger** [comment]
Just pushed a change to `xfce4-panel` to enable `gtk-layer-shell` support on Wayland. Hopefully that solves the issue of the panel floating in the middle of the screen with window decorations... xD

**Comment by Ernesto2660** [comment]
I maked the update and it's ok for me now. Thank's a lot for the job you done.
Best regards

**Comment by Ernesto2660** [comment]
Hi
When I left-click on the desktop, no menu appears.
Best regrads

**Comment by Ernesto2660** [comment]
Hi
This appeared after a reinstallation
Best regards

**Comment by Ernesto2660** [comment]
Hi
The bluetooth connection does not work, message: “br connection busy”.
Best regards

**Comment by EbonJaeger** [comment]
> Hi When I left-click on the desktop, no menu appears. Best regrads

Right click should bring up the menu, not left click.

**Comment by Ernesto2660** [comment]
> > Hi When I left-click on the desktop, no menu appears. Best regrads
> 
> Right click should bring up the menu, not left click.

Sorry
I made a mistake. It's the right click doesn't work.

**Comment by Ernesto2660** [comment]
> > > Hi When I left-click on the desktop, no menu appears. Best regrads
> > 
> > 
> > Right click should bring up the menu, not left click.
> 
> Sorry I made a mistake. It's the right click doesn't work.

to be more precise: after removing all desktop icons

**Comment by Ernesto2660** [comment]
Me again. I found the solution in settings, 
desktop tab, 
desktop icons 
and checking either icons for minimized applications or 
for a full menu, file/launcher icons. 
Sorry for all these messages. 
I do regret the old version on this point, though, because by deleting the tabs on the desktop, the right-click still displayed the whole menu. 
Best regards

**Comment by Ernesto2660** [comment]
And after a reinstallation, the bluetooth works.

**Comment by EbonJaeger** [comment]
This is now ready for review. Packages have been double-bumped to ensure that anyone who tested the pre-release version gets the full update.

**Review by ermo — APPROVED** [review]
LGTM, thanks!

**Comment by Ernesto2660** [comment]
Hello
Here's the configuration of my computer with XFCE 4.2 installed on an external SSD. 
Capture d’écran_2024-12-16_09-47-27
 
This morning I tried to install
Capture d’écran_2024-12-16_09-22-11

And here is the result. The update doesn't work. 
Capture d’écran_2024-12-16_09-18-03

I didnt receive the last complete update. ( This is now ready for review. Packages have been double-bumped to ensure that anyone who tested the pre-release version gets the full update.)
Thanks. have a nice dday

**Comment by Ernesto2660** [comment]
For completeness, here is the fastfetch of the ssd with XFCE 4.2
Capture d’écran_2024-12-16_10-04-33

**Comment by Ernesto2660** [comment]
I tried to install the new updates (photo attached), but it was impossible. I couldn't install them one by one, so I'm going to reinstall the system and see if the updates are possible.

**Comment by Ernesto2660** [comment]
12172024a
here is after a new installation and a try to install xfce 4.2

**Comment by EbonJaeger** [comment]
@Ernesto2660 remove the testing repository; all the packages are now in the Solus Unstable repository.

```bash
sudo eopkg rr "XFCE4 Testing"

**Comment by Ernesto2660** [comment]
OK. It works.
Thank You

**Pull request merged**
