### PR TITLE
libboost: update to 1.83.0 & rebuilds

### PR DESCRIPTION
**Pull request by joebonrichie**
**Summary**

Update libboost to 1.83.0

**Test Plan**

Install rebuilds repo, test some applications against libboost

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
Given that we've already had one toolchain update I'm inclined to have the LLVM PR finished and merged before rebuilding this one and getting it merged. I assume at least a few of these packages are built by LLVM and we might as well do fewer rebuilds if we can.

**Comment by GZGavinZhao** [comment]
I'll try to get the LLVM 16 PR finished this week so that we don't have to wait further.

**Comment by TraceyC77** [comment]
Depends on #251

**Comment by joebonrichie** [comment]
Not all the `abi_used_symbol` info will be up to date as not everything has been rebuild against the newest toolchain, is that a blocker for merge?

**Comment by ReillyBrogan** [comment]
Personally I'd like to see a full rebuild with all the changes we made. Should be pretty straightforward with the rebuild script I shared in Matrix. If you need me to I can do the rebuilds for you as well?

**Comment by joebonrichie** [comment]
Just realized this is still blocked on mongodb. No longer builds against gcc-13

**Review by ermo — APPROVED** [review]
Joey asked someone to approve this, so that's hereby done.

**Pull request merged**
