### PR TITLE
xfce4-xkb-plugin: add at v0.8.3

### PR DESCRIPTION
**Pull request by AlexanderZhirov**
**Summary**

Add a new plugin to switch keyboard layouts on the Xfce4 panel

**Test Plan**

- Add the keyboard layouts plugin to the XFCE4 panel
- Switch the layout

**Checklist**

- [X] Package was built against unstable
- [X] Package was built and tested against stable

### CODE REVIEW

**Review by EbonJaeger — CHANGES_REQUESTED** [review]
The build dependencies are also not in alphabetical order; see the linter warning in the Files tab. You can run `go-task check` locally to get faster feedback on linter problems. :)

**Comment by AlexanderZhirov** [comment]
@EbonJaeger I have made the necessary edits 👌

**Comment by AlexanderZhirov** [comment]
I misstated the dependencies by referring to the [Alpine build](https://git.alpinelinux.org/aports/tree/community/xfce4-xkb-plugin/APKBUILD) 😁

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks! :)

**Pull request merged**
