### PR TITLE
wireshark: fix launching dumpcap

### PR DESCRIPTION
**Pull request by AlexanderZhirov**
**Summary**
    
Fix for launching dumpcap from under the user

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
Do you have a reference of what capabilities dumpcamp needs specifically?

**Comment by AlexanderZhirov** [comment]
@ReillyBrogan https://wiki.wireshark.org/CaptureSetup/CapturePrivileges#setting-network-privileges-for-dumpcap-if-your-kernel-and-file-system-support-file-capabilities

**Comment by ReillyBrogan** [comment]
So unfortunately I was just reminded that the ypkg package manager doesn't support having file capabilities in packages. Hopefully we can fix this once we take ypkg and eopkg to python 3, but for now I'm going to close this as this won't actually do anything on end user systems.

**Comment by ReillyBrogan** [comment]
@AlexanderZhirov We added xattr support for wireshark and this is done now.

**Pull request closed without merging**
