### PR TITLE
hplip: update to 3.23.12

### PR DESCRIPTION
**Pull request by TraceyC77**
After installing or updating this package, run `hp-plugin` on command line before attempting to add a printer, print or scan.

**Summary**

Added support for new devices.

Solus:
- Updated release notes URL, added homepage.
- Updated patch after upstream code update.
- Added metainfo file.

**Test Plan**
Verified
- plugin was installed successfully by `hp-plugin`
- previously installed HP Printer is still configurable in Print Settings
- hp-toolbox launches HP Device Manager successfully
- ability to remove and re-add printer / fax in hp-toolbox (Note: must first run hp-plugin)
- can start Simple Scan
- scanning works
- printing works

**Known Issue**
The HP Device Manager UI may display an error on the status tab of the printer 'Device is busy, powered down or unplugged (5002)'

Workaround: Manage the printer via System Settings rather than HP Device Manager. Printing is still successful.

### CODE REVIEW

**Comment by davidjharder** [comment]
builddeps and rundeps are out of order

**Review by davidjharder — CHANGES_REQUESTED** [review]
Dependencies should be re-ordered

**Comment by TraceyC77** [comment]
That'll teach me to close the tab before checks are completed. Build order fixed. Checks passed.

**Review by davidjharder — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
