### PR TITLE
qwt: update to 6.2.0

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Release notes can be found [here](https://qwt.sourceforge.io/qwtchangelog.html).
- Added homepage to package.yml

**Test Plan**
- Built and installed qgis against this.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by davidjharder — CHANGES_REQUESTED** [review]
You have changes in `abi_libs`: This will need to include rebuilds for `gnuradio` and `qgis`
You can include them as additional commits on this PR

**Comment by androidnisse** [comment]
@davidjharder I think this is fixed now.

**Comment by davidjharder** [comment]
Small thing: Please correct the title of commit "rebuild against qwt" to "qgis: rebuild against qwt 6.2" to match the other commit

Other than that, looks good!

**Comment by androidnisse** [comment]
> Small thing: Please correct the title of commit "rebuild against qwt" to "qgis: rebuild against qwt 6.2" to match the other commit
> 
> Other than that, looks good!

I think I have fixed that now.

**Comment by davidjharder** [comment]
Yep, I think that's it.

Just so you know: for rebuild commits, you can just write a single line message: "package: rebuild against whatever". You don't need to add a `**summary**` section below.

**Review by davidjharder — APPROVED** [review]

**Pull request merged**
