### PR TITLE
Add ent to repo and use it for taskfile

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- ent: Add at v0.1.0
- Taskfile.yml: Add new command to check package updates

**Test Plan**

- Check updates on packages repo
- Use `go-task updatecheck`

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by malfisya** [comment]
Not sure about that version number and also kinda ironic the tools to check monitoring.yml doesn't have it. lol

**Comment by ermo** [comment]
> Not sure about that version number and also kinda ironic the tools to check monitoring.yml doesn't have it. lol

It's an early prototype. Had to start somewhere.

**Comment by Staudey** [comment]
Current dev version seems to be `0.1.0`

https://github.com/serpent-os/ent/blob/6f6f7c4010810ec2ee2a773d174f7c5daacc583f/Cargo.toml#L3

**Comment by malfisya** [comment]
> > Not sure about that version number and also kinda ironic the tools to check monitoring.yml doesn't have it. lol
> 
> It's an early prototype. Had to start somewhere.

Definitely and it already works well to check update. Oh, look it has [one](https://release-monitoring.org/project/375595/) now.

**Review by ermo — APPROVED** [review]
Why not. Thanks!

**Pull request merged**
