### PR TITLE
repo-wide : Add work around for cargo issue and monitoring.yml

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Add work around for cargo [issue](https://github.com/getsolus/solbuild/issues/87/)                       
- Add monitoring.yml

### CODE REVIEW

**Comment by joebonrichie** [comment]
This also affects librsvg which is cargo wrapped around with autotools. Looking more like a sccache issue to me.

**Comment by joebonrichie** [comment]
The librsvg hang post-link which indicates an sccache issue more than a cargo issue

**Comment by malfisya** [comment]
Should i edit the commit message? And the comment on package.yml?

**Comment by malfisya** [comment]
Will be fixed by this PR https://github.com/getsolus/solbuild/pull/93 and new release of solbuild (1.6.2)

**Pull request closed without merging**
