### PR TITLE
Update libcacard and rebuild revdeps

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- libcacard: Update to 2.8.1
- spice: Rebuild against libcacard
- spice-gtk: Rebuild against libcacard
- qemu: Rebuild against libcacard

### CODE REVIEW

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Review by EbonJaeger — CHANGES_REQUESTED** [review]
Oops, looks like it has to be rebased. Might as well check if any of these need appstream metainfo added, too.

**Comment by malfisya** [comment]
`qemu` ships a desktop file, not sure if it worth adding appstream metainfo to it. Will revisit it later

**Review by EbonJaeger — APPROVED** [review]
LGTM! I'll leave it to you if you want to figure out the appinfo stuff or not.

**Pull request merged**
