### PR TITLE
postgresql: Update to 17.0

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Release notes can be found [here](https://www.postgresql.org/about/news/postgresql-17-released-2936/).
- Resolves https://github.com/getsolus/packages/issues/3962
- This update requires manual migration of databases. Instructions can be found in the [Solus Help Center](https://help.getsol.us/docs/user/software/development/postgresql#updating-to-17).

**Test Plan**
- Started the systemd service. Logged in with the default user and listed the default databases.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by silkeh — CHANGES_REQUESTED** [review]
This needs an accompanying PR for the documentation. See https://github.com/getsolus/help-center-docs/pull/390 for the one for PostgreSQL 16.

**Comment by androidnisse** [comment]
> This needs an accompanying PR for the documentation. See [getsolus/help-center-docs#390](https://github.com/getsolus/help-center-docs/pull/390) for the one for PostgreSQL 16.

Added that now.

**Comment by silkeh** [comment]
Thanks! Can you amend your commit to link the upgrade docs so it shows up in the changelog? Eg:

```
This update requires manual migration of databases. Instructions can be found in the [Solus Help Center](https://help.getsol.us/docs/user/software/development/postgresql#updating-to-17).
```

Additionally, be aware that this is not something that can be landed during the ISO release freeze as 1) it's very much not a leaf package, and 2) included in the actual ISO (the CI missed that, apparently :disappointed:)

**Comment by androidnisse** [comment]
> Thanks! Can you amend your commit to link the upgrade docs so it shows up in the changelog? Eg:
> 
> ```
> This update requires manual migration of databases. Instructions can be found in the [Solus Help Center](https://help.getsol.us/docs/user/software/development/postgresql#updating-to-17).
> ```
> 
> Additionally, be aware that this is not something that can be landed during the ISO release freeze as 1) it's very much not a leaf package, and 2) included in the actual ISO (the CI missed that, apparently 😞)

No problems, updated commit message and Github message.

**Pull request merged**
