### PR TITLE
hunspell-da: update to 2.8

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Fixed licenses
- Added homepage to package.yml

**Test plan**
- Installed and loaded in LibreOffice

**Check list**
- [X] Package was built and tested against unstable.

### CODE REVIEW

**Comment by algent-al** [comment]
I am looking at `README_da_DK.txt` file. looks like licenses were fine.
```
Stavekontrolden - Danish dictionary files for Hunspell and thesaurus files for MyThes
Version 2.8.001 - 05-09-2023
da_DK.dic, da_DK.aff, th_da_DK.dat, th_da_DK.idx: © 2020 Foreningen for frit tilgængelige sprogværktøjer - http://www.stavekontrolden.dk
These files are published under the following open source licenses:

GNU GPL version 2.0 - https://www.gnu.org/licenses/gpl-2.0.html
GNU LGPL version 2.1 - https://www.gnu.org/licenses/lgpl-2.1.html
Mozilla MPL version 1.1 - https://www.mozilla.org/en-US/MPL/1.1/

This dictionary is based on data from Det Danske Sprog- og Litteraturselskab
(The Danish Society for Language and Literature), https://dsl.dk.
Thanks to Lyngby-Taarbæk Kommune, Gribskov Kommune and Region Midtjylland for financial support to the thesaurus project.
```

**Comment by TraceyC77** [comment]
@algent-al  You haven't marked the PR as changed requested. Can this be merged then?

**Review by algent-al — CHANGES_REQUESTED** [review]
Judging from the content of `README_da_DK.txt` file, licenses were actually correct.

**Comment by androidnisse** [comment]
@algent-al yes you are correct, I checked the website where they changed but not the readme. Should be fixed now.

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
