### PR TITLE
nvidia-beta-driver: Update to 550.40.07

### PR DESCRIPTION
**Pull request by Staudey**
**Summary**

Changes:
- Fixed an issue that sometimes caused Wayland applications to run at less than one frame per second on Maxwell, Volta, and Pascal series GPUs.
- Fixed a bug that caused an intermittent drop in desktop framerate.
- Fixed a bug that caused "Flip event timeout" messages to be printed to the system log when displays are hotplugged when nvidia-drm is loaded with the `fbdev=1` kernel module parameter.
- Fixed intermittent Xid errors on Horizon Zero Dawn, Metro Exodus, Forza Horizon 5, and Halo Infinite.
- Fixed a bug which prevented the "NoMaxPClkCheck" mode validation token from working on single-link TMDS (e.g. DVI, HDMI) outputs.
- Fixed a bug that allowed VRR displays to be driven below their minimum refresh rate, resulting in a blank or flickering image.
- Added an application profile to improve Kwin performance on hybrid GPU systems by setting OGL_DEDICATED_HW_STATE_PER_CONTEXT=ENABLE_ROBUST.
- Updated the build process for NVIDIA kernel modules to honor the `INSTALL_MOD_DIR` Kbuild environment variable.
- Added support for R8, GR88 and YCbCr GBM formats.
- Optimized the X driver headless framerate limiter to more closely mimic upstream behavior and prevent it from activating in inconvenient situations.
- Added a new X config option "LimitFrameRateWhenHeadless" to disable the headless framerate limiter.
- Fixed a bug that prevented Gamescope from running when using the NVIDIA Open GPU Kernel modules.
- Use transparent huge pages when available for the .text section. This is done through madvise() calls, and requires CONFIG_READ_ONLY_THP_FOR_FS.
- Added beta-quality support for GeForce and Workstation GPUs to open kernel modules.
- Changed the name visible in /proc/devices of NVIDIA devices and the NVIDIA control device from "nvidia-frontend" to "nvidia" and "nvidiactl"

**Test Plan**

- Rebooted
- Launched Steam
- Played the games "b" (Proton) and "Core Keeper" (native)

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by joebonrichie** [comment]
i can't login to any wayland sessions with this one, anyone else?

**Comment by Staudey** [comment]
> i can't login to any wayland sessions with this one, anyone else?

Is this the same issue you had with the 545 series, or a new one?

Currently trying to fix my GNOME session in general so I can test ^^

**Comment by joebonrichie** [comment]
> > i can't login to any wayland sessions with this one, anyone else?
> 
> Is this the same issue you had with the 545 series, or a new one?
> 
> Currently trying to fix my GNOME session in general so I can test ^^

New one

**Comment by Staudey** [comment]
I see, the previous issue was just random instability or something?

Unfortunately my GNOME session seems to be completely borked atm so I can't test Wayland login until I figure this out (first couple things I tried didn't work)

**Review by ReillyBrogan — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
