### PR TITLE
font-intel-one-mono : Add at v1.3.0

### PR DESCRIPTION
**Pull request by uni-dos**
**Summary**

Add the intel-one-mono font, which is font intended for programmers

**Test Plan**

- Set font in terminal, your favorite text editor, or in all applications.

**Checklist**

- [x] Package was built and tested against unstable

Resolves https://github.com/getsolus/packages/issues/2580

### CODE REVIEW

**Comment by malfisya** [comment]
Please follow this [procedure](https://help.getsol.us/docs/packaging/procedures/request-a-package), before submitting a PR for new package. Thank you.

**Comment by davidjharder** [comment]
@uni-dos I approved your request. Please add `Resolves https://github.com/getsolus/packages/issues/2580` to your commit message and PR description.

**Comment by uni-dos** [comment]
I believe I did it correctly. I had some extra commits by accident. Hopefully I merged them.

**Review by davidjharder — APPROVED** [review]
Looks good to me. Welcome to Solus packaging!

**Pull request merged**
