### PR TITLE
repo: add Git hooks

### PR DESCRIPTION
**Pull request by silkeh**
**Summary**

Add Git hooks and initialisation:

- Task for initializing the hooks.
- Pre-commit hook that runs the package checks for the files to be committed.
- Post-checkout hook that runs `go-task init`.

**Test Plan**

- Check out this PR, eg: `git pr 466` (from `git-extras`).
- Run `go-task init`.
- Switch to main or any other branch and continue working normally.

**Checklist**

- [x] ~~Package was built and tested against unstable~~ n/a

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
Probably needs docs.

**Comment by silkeh** [comment]
I just removed some logic around adding the package scopes to commit messages, as it was [too trigger happy in a rebase](https://github.com/getsolus/packages/commit/87eddb50606e91b547ed885540b1c40273db92af).

**Comment by EbonJaeger** [comment]
Ah, that would do it. Sorry.

**Review by EbonJaeger — APPROVED** [review]
I've been using this for at least a week. It definitely makes life a bit easier.

**Review by ReillyBrogan — APPROVED** [review]
LGTM

**Pull request merged**
