### PR TITLE
fritzing-parts: Update to 1.0.2

### PR DESCRIPTION
**Pull request by palto42**
**Summary**

Depends on #1529

Align parts with latest app release.

Changelog:

- [Commit log v1.0.2](https://github.com/fritzing/fritzing-parts/commits/1.0.2)

**Test Plan**

- Installed and tested with Fritzing v1.0.2

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by algent-al — CHANGES_REQUESTED** [review]
Please set a homepage.

**Comment by palto42** [comment]
Added the homepage and reversed the dependency to Fritzing app update as I think that actually the build of the Fritzing parts depends on the new app version.

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Review by ReillyBrogan — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
