### PR TITLE
firewalld: Update to 2.1.1

### PR DESCRIPTION
**Pull request by EbonJaeger**
**Summary**
Changelog available [here](https://github.com/firewalld/firewalld/releases/tag/v2.1.1).

Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>

**Test Plan**

Restart the computer and verify that the applet appears in the tray and that the firewall appears to be active.

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by EbonJaeger** [comment]
Lemme fix the build deps.

**Review by davidjharder — COMMENTED** [review]
You just moved the "patterns" to a different position right? I don't see changes.

**Comment by EbonJaeger** [comment]
Correct, just moved them down to the bottom.

**Review by davidjharder — APPROVED** [review]
Looks good!

**Pull request merged**
