### PR TITLE
hal-flash: deprecate

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Resolves https://github.com/getsolus/packages/issues/2063

**Test Plan**
- Ran the script for removal. Checked the package was added.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by EbonJaeger** [comment]
It's really amusing how you somehow ended up with one line using tabs and the other line using spaces xD

**Comment by androidnisse** [comment]
> It's really amusing how you somehow ended up with one line using tabs and the other line using spaces xD

I blame vim looks fine there ^^ should i fix it?

**Comment by EbonJaeger** [comment]
GitHub by default uses a much larger tab space when displaying tabs, whereas by default Vim (and most other editors) use the same width for one tab and 4 spaces (or 2 spaces, depending on the language), so that's why it only shows up here.

It would be nice just for the PR if both lines used tabs or spaces; the file itself already is a mess of both ways, at least last I checked.

**Comment by androidnisse** [comment]
> GitHub by default uses a much larger tab space when displaying tabs, whereas by default Vim (and most other editors) use the same width for one tab and 4 spaces (or 2 spaces, depending on the language), so that's why it only shows up here.
> 
> It would be nice just for the PR if both lines used tabs or spaces; the file itself already is a mess of both ways, at least last I checked.

Did I fix it?

**Comment by EbonJaeger** [comment]
Yep!

**Review by TraceyC77 — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
