### PR TITLE
heroic-games-launcher: Update to 2.12.1

### PR DESCRIPTION
**Pull request by infinitymdm**
**Summary**

Update Heroic to 2.12.1

Fixes some log spam and a few other such small bugs. Full changelog [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/compare/v2.11.0...v2.12.1)

**Test Plan**

Launch Heroic. Fiddle with settings, navigate pages, and make sure things check out.

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by algent-al** [comment]
Please add **Changelog** and **Test Plan** in commit body.

**Comment by infinitymdm** [comment]
> Please add **Changelog** and **Test Plan** in commit body.

Is this a newly changed requirement? I usually just have these in the PR description as in #1553

**Comment by davidjharder** [comment]
No, I should have asked you to do it for citra too.


Otherwise the software center changlog is a little bare:

Screenshot_20240206_183512

**Comment by infinitymdm** [comment]
Ah, ok. I'll try to make this part of my procedure going forward.

**Comment by infinitymdm** [comment]
Should be good to go now. I'll make sure I include summary and test plan in all my future update commits. Thanks!

**Review by davidjharder — APPROVED** [review]
Thanks for the update

**Pull request merged**
