### PR TITLE
Handbrake: Use libvpl and enable nvenc/nvdec

### PR DESCRIPTION
**Pull request by ReillyBrogan**
**Summary**
- onevpl is now libvpl, adopting a new versioning scheme
- Update nv-codec-headers
- Rebuild handbrake with libvpl, enable nvdec/nvenc

**Test Plan**
- @codewizard1975 will test to see if the Intel QSV is workign
- Someone with a Nvidia GPU can test nvdec/nvenc

### CODE REVIEW

**Review by EbonJaeger — COMMENTED** [review]
Deps for libvpl aren't quite in alphebetical order.

**Comment by ReillyBrogan** [comment]
Fixed!

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Comment by EbonJaeger** [comment]
Since it's Friday, do we want to merge this after sync?

**Pull request merged**
