### PR TITLE
Update KDE Frameworks to 5.110.0

### PR DESCRIPTION
**Pull request by joebonrichie**
## Summary

https://kde.org/announcements/frameworks/5/5.110.0/

## Test Plan

Test some KDE Gear applications like konsole and dolphin

## Checklist

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by joebonrichie** [comment]
Wait til history generation in metadata.xml is fixed before merge. Testing `rebuild-template-script.sh`  rewrite for monorepo.

**Comment by ReillyBrogan** [comment]
```
Message: 1
Date: Mon, 18 Sep 2023 18:59:16 +0200
From: Albert Astals Cid <[aacid@kde.org](mailto:aacid@kde.org)>
To: [distributions@kde.org](mailto:distributions@kde.org)
Subject: Please patch your kio
Message-ID: <7468653.eRudhRZ7iK@xps15>
Content-Type: text/plain; charset="us-ascii"

If you're shipping kio v5.110.0 please include

 https://invent.kde.org/frameworks/kio/-/commit/48322f44323a1fc09305d66d9093fe6c3780709e

I'm getting daily crash reports on Okular because of it.

Cheers,
  Albert
  ```

**Comment by joebonrichie** [comment]
included kio patch now

**Comment by joebonrichie** [comment]
Think it's better to land this post sync now

**Comment by joebonrichie** [comment]
merged manually as workflow isn't setup properly for monorepo yet.

**Pull request closed without merging**
