### PR TITLE
libresprite: Include 1.0

### PR DESCRIPTION
**Pull request by nazar-stasiv**
**Summary**
- Initial inclusion of animated sprite editor
- [Resolves 2213](https://github.com/getsolus/packages/issues/2213)

**Test Plan**
- open sprite-sheet, play animation

**Checklist**
- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by joebonrichie** [comment]
Can you squash commits and force push

**Comment by nazar-stasiv** [comment]
> Can you squash commits and force push

just squashed.

**Review by nazar-stasiv — COMMENTED** [review]
.

**Comment by nazar-stasiv** [comment]
Doesn't look like linter completed its job properly. I'll reopen so it runs through the patch again.

**Pull request closed without merging**
