### PR TITLE
Add sort_deps python script by Harvey and relevant go-task

### PR DESCRIPTION
**Pull request by Justinzobel**
**Summary**

Add sort_deps python script by Harvey and relevant go-task

**Test Plan**

Tested go-task sort on a package, deps sorted.

### CODE REVIEW

**Comment by ermo** [comment]
Same as for the ypkg PR; looping in Silke and joey respectively (Silke for the linter py experience, Joey because he's doing the py3 upgrade and ypkg-py3 is on the horizon)

**Comment by joebonrichie** [comment]
checkdeps and rundeps as well

**Comment by silkeh** [comment]
I don't think this PR matches the logic in the CI (see [here](https://github.com/getsolus/packages/blob/main/common/CI/package_checks.py#L333)). The logic in the CI is basically as follows:

1. Replace values in dictionary by sorted equivalents if item is a dictionary.
2. Sort items with the following preference:
   1. `pkgconfig32`
   2. `pkgconfig`
   3.  package name or dictionary key.

But it would probably be preferable to have a single bit of code defining this if possible.

**Comment by Staudey** [comment]
Why do we sort `pkgconfig32()` before `pkgconfig()`? Seems like it just complicates things without apparent benefit
(because otherwise you could just sort all the pkgconfigs as a whole, and `pkgconfig()` would come first, instead of 32)
[also I'd have to add that to the docs ^^]

**Comment by silkeh** [comment]
> Why do we sort pkgconfig32() before pkgconfig()?

The CI script checks it this way because more packages have `pkgconfig32` first, and the added complexity was negligible.

**Review by silkeh — CHANGES_REQUESTED** [review]
Whoops, I forgot to properly leave a review. See [this comment](https://github.com/getsolus/packages/pull/1659#issuecomment-1951422521).

**Comment by ermo** [comment]
@Justinzobel This is py2. Are you planning on working more on this?

**Comment by Justinzobel** [comment]
> @Justinzobel This is py2. Are you planning on working more on this?

No. I've reached peak plate filling again and don't have the time or energy to continue this. If anyone wants to take it over please do, if not feel free to close.

**Pull request closed without merging**
