### PR TITLE
lynx: update to 2.9.0

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**

- Update lynx to 2.9.0
- Add "homepage" to package.yml part of https://github.com/getsolus/packages/issues/411
- Change log can be found [here](https://lynx.invisible-island.net/lynx2.9.0/breakout/CHANGES).

**Test Plan**
- Installed and checked some web pages.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by davidjharder** [comment]
Please add the "Summary" and "Test Plan" blocks to your commit message as well, otherwise that information is not available in `solus-sc` (Software Center)

**Review by davidjharder — CHANGES_REQUESTED** [review]
.

**Comment by androidnisse** [comment]
All commits should be fine now @davidjharder

**Review by davidjharder — APPROVED** [review]
Looks good, sorry for the delay!

**Pull request merged**
