### PR TITLE
unsnap: Add at 2023.03.11

### LINKED ISSUE #323: unsnap
### Homepage

https://github.com/popey/unsnap

### Why should this be included in the repository?

This automates the process of moving from Snap to Flatpak.

### Are we allowed to redistribute it?

MIT

### Who and how many users do you anticipate will use this software?

Everyone using snaps.

### Link to source archive file

https://github.com/popey/unsnap/archive/refs/heads/main.tar.gz

### PR DESCRIPTION
**Pull request by silkeh**
**Summary**

Initial inclusion of `unsnap` at the last upstream commit. It includes a patchset that adds support for `eopkg`.

Resolves #323

**Test Plan**

Run `sudo unsnap auto` to automatically migrate snaps to flatpak.

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by Staudey** [comment]
Is the patch for the README really necessary, as it doesn't seem to be included in the final package?

**Comment by ermo** [comment]
Works for me per [d3fd80e](https://github.com/getsolus/packages/pull/3208/commits/d3fd80eed28d3e2e3f3b1ec1cedfb0a69c6b914c)

**Comment by silkeh** [comment]
I have included additional patches to improve the user experience. In particular, `unsnap` now disables all remaining systemd units.

> Is the patch for the README really necessary, as it doesn't seem to be included in the final package?

No, but it is part of the patchset I've rebased from an open PR. I'm hoping to upstream it at some point.

**Comment by silkeh** [comment]
I've made sure that it works with the wrapper script from #3211. Should be good to go now!

**Review by ermo — DISMISSED** [review]
I was confused when just running `sudo unsnap`, because there is no help output and the script didn't give me a message at the end telling me how to actually _effectuate_ the changes?

Suggestion: Consider making `sudo unsnap` print out a message telling the user to:
- check out the help page
- use `sudo unsnap auto` to actually remove snaps and snapd

**Comment by silkeh** [comment]
@ermo: I added a message with clarification. Let me know what you think!

**Review by ermo — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
