### PR TITLE
solbuild: Fix homepage

### PR DESCRIPTION
**Pull request by Staudey**
**Summary**

This updates the solbuild homepage to the new GitHub org

**Test Plan**

Checked the package referenced the correct homepage

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by algent-al — DISMISSED** [review]
GitHub Actions / Checks are reporting two problems.
Release number need a bump and rundeps order.

**Comment by Staudey** [comment]
Ha, every time I edit something that changes the pspec I forget to bump because I don't notice it by the missing diff ^^

So we really want the subpackage dependencies ordered in the same hierarchy as the other deps? Seems a bit ugly, especially when it comes to situations like this: https://github.com/getsolus/packages/pull/1515/files#diff-3582b853055fc5d17ef157483426cceea408317bf4d4af86707fde3e9c15039cL48

Shouldn't they be on a separate level, like pkgconfigs?
Sorry if this has already been discussed.

**Comment by ReillyBrogan** [comment]
> Seems a bit ugly, especially when it comes to situations like this

Yeah it's hideous you're not wrong.

**Review by ReillyBrogan — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
