### PR TITLE
openjpeg: update to 2.5.2

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Release notes can be found [here](https://github.com/uclouvain/openjpeg/blob/v2.5.2/CHANGELOG.md).

**Test Plan**
- Installed and started packages dependent on this.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by malfisya — CHANGES_REQUESTED** [review]
Can you change the release notes to the version specified tags? Using master will means it will change anytime a new release happen

**Comment by malfisya** [comment]
Sorry for not specifying. The commit message too needs the change. I know this is a nitpick, but please bear with me.

**Comment by androidnisse** [comment]
> Sorry for not specifying. The commit message too needs the change. I know this is a nitpick, but please bear with me.

Fixed.

**Review by malfisya — APPROVED** [review]
LGTM. Thanks!

**Comment by EbonJaeger** [comment]
It looks like the first two patches are still valid. Likely, the third one is, too. Does the package still build with them included?

**Comment by androidnisse** [comment]
> It looks like the first two patches are still valid. Likely, the third one is, too. Does the package still build with them included?

It builds now with the patches but did not when I first updated it. I have added all back now.

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
