### PR TITLE
blender: Update to v4.2.3

### PR DESCRIPTION
**Pull request by ReillyBrogan**
Changes:
- Update Blender to v4.2.2
- Package gcc-13 since CUDA doesn't support GCC 14.

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
I tossed the built eopkgs for this up at https://shared.getsol.us/reilly/2024-10-blender/ so you don't need to build it to test it. `gcc-13` is only used as a builddep, no need to install it if you're just testing the blender package.

**Comment by androidnisse** [comment]
Could this be done here as well or should it be its own PR?

https://github.com/getsolus/packages/issues/3708

**Comment by luzpaz** [comment]
Note 4.2.3 is out (https://www.blender.org/download/lts/4-2/#versions)

**Comment by ReillyBrogan** [comment]
> Could this be done here as well or should it be its own PR?
> 
> #3708

Done

**Pull request merged**
