### PR TITLE
soqt: update to 1.6.2

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Link build artifacts to Coin v4.0.2
- Update CI workflow and build matrix
- Fixed numerous typos found with codespell

**Test Plan**
- Checked it installed correctly.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by EbonJaeger** [comment]
For the test plan, could you make sure that `python-pivy` builds against this version? Looks like that's what was done in the past.

**Comment by androidnisse** [comment]
> For the test plan, could you make sure that `python-pivy` builds against this version? Looks like that's what was done in the past.

It does not build on the version in repo. There is a newer version that does build but it is tagged as pre release. So should we just wait until that is tagged stable?

**Comment by EbonJaeger** [comment]
It's been a while since the repository has seen activity, so I won't hold my breath. Fedora is building with a patch containing all the commits since the last stable release, and Arch is using the pre-release tarball. Since `pivy` has problems besides (or entirely separate from) SoQt, we'll probably have to do the same sooner or later.

**Comment by androidnisse** [comment]
> It's been a while since the repository has seen activity, so I won't hold my breath. Fedora is building with a patch containing all the commits since the last stable release, and Arch is using the pre-release tarball. Since `pivy` has problems besides (or entirely separate from) SoQt, we'll probably have to do the same sooner or later.

Yea, I will leave this one for now then.

**Comment by androidnisse** [comment]
@EbonJaeger there was a release of pivy so now it all builds. Could you please review this?

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
