### PR TITLE
sxiv: deprecate

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Replaced by nsxiv
- Resolves https://github.com/getsolus/packages/issues/3006

**Test Plan**
- Checked the files were deleted.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Comment by malfisya** [comment]
@androidnisse Did you ever file a deprecation PR? (Just want to make sure that you followed the usual steps.)

**Comment by androidnisse** [comment]
> @androidnisse Did you ever file a deprecation PR? (Just want to make sure that you followed the usual steps.)

No, this is first. Copied one old of yours for this.

**Comment by malfisya** [comment]
Ok, so for deprecation we actually only edit `distribution.xml.in` file. Then you run `merged_repos.sh` script inside the `repo_data` directory to automatically edit the `distribution.xml` file. The script ensure the formatting is consistent. (This should be really documented somewhere). Can you do that?

**Comment by androidnisse** [comment]
> Ok, so for deprecation we actually only edit `distribution.xml.in` file. Then you run `merged_repos.sh` script inside the `repo_data` directory to automatically edit the `distribution.xml` file. The script ensure the formatting is consistent. (This should be really documented somewhere). Can you do that?

No problem. I've ran the script now and pushed what changed.

**Review by malfisya — APPROVED** [review]

**Pull request merged**
