### PR TITLE
yubico-authenticator: update to 6.4.0

### PR DESCRIPTION
**Pull request by TraceyC77**
**Changelog:**

- UI: Major UI overhaul, with improvements including:
    - Add new UI layouts for wider windows to better utilize screen space.
    - Add YubiKey personalization through custom naming and theme color.
    - Split FIDO/WebAuthn into multiple sections.
    - Move factory reset functionality into a single dialog, from the individual sections.
- Add support for Yubico OTP provisioning.
- PIV: Display more information about keys and certificates.
- PIV: Add output format for public key when generating keys.
- Desktop: Window hidden/shown state no longer saved when closing the app, use --hidden to start the app in a hidden to systray state.
- Desktop: Fix FIDO reset over NFC.
- Windows: Add option to launch Windows Settings for FIDO management.
- Android: Increase read timeout for NFC, improving compatibility with older YubiKeys.

Full release notes available [here](https://github.com/Yubico/yubico-flutter/releases)

**Test Plan**
- YubiKey Authenticator launches from the app menu
- YubiKey recognized
- Logged into an account with 2 factor auth successfully

### CODE REVIEW

**Comment by EbonJaeger** [comment]
It looks like there might be a weird character in front of the first changelog item. Not sure what it is.

**Review by EbonJaeger — DISMISSED** [review]
LGTM, thanks!

**Comment by EbonJaeger** [comment]
oh wait

**Comment by EbonJaeger** [comment]
This is the one with the weird character in the commit message.

**Comment by TraceyC77** [comment]
Commit message has been fixed

**Review by EbonJaeger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
