### PR TITLE
noto-sans-ttf: update to 24.1.1

### PR DESCRIPTION
**Pull request by Staudey**
**Summary**

The noto fonts project has switched repositories. This updates our package to the latest released tag.

Note: Previous releases in the new repo excluded some important fonts like Kufi Arabic, but now most things are in place. The Noto Display fonts have been discontinued though (see [this issue](https://github.com/notofonts/notofonts.github.io/issues/16)).

Additionally the noto-emoji subproject is updated to the final [Unicode 15.1](http://blog.unicode.org/2023/09/announcing-unicode-standard-version-151.html) release.

**Test Plan**

1. Set my system fonts to Noto
2. Wrote a few lines in LibreOffice using Noto
3. Tested lime emoji 🍋‍🟩

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by davidjharder** [comment]
Hey @Staudey are you planning further changes to this PR?

**Comment by Staudey** [comment]
I guess it's ready for review (now that I've also fixed the release number :laughing:)

**Comment by davidjharder** [comment]
FYI, I told @nelsontkq he could take a stab at updating OBS, wasn't sure if you had time for that.

**Review by davidjharder — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
