### PR TITLE
fb2converter: Fix build server failure

### PR DESCRIPTION
**Pull request by nazar-stasiv**
**Summary**
- set TERM env variable

**Test Plan**
- The error is reproducible on build server

**Checklist**
- [X] Fingers crossed it works

### CODE REVIEW

**Review by davidjharder — APPROVED** [review]
Let's give it a shot

**Comment by joebonrichie** [comment]
You need to figure out how to disable go-task from outputting color or strip out the the tput command in Taskfile.yml.

**Comment by joebonrichie** [comment]
They need to be checking for `TERM=dumb` here not just the existence of the variable.

https://github.com/rupor-github/fb2converter/blob/v1.75.1/Taskfile.yaml#L20

**Comment by davidjharder** [comment]
oh, they use taskfile! I assumed it was coming from our scripts. Thanks joey!

**Comment by davidjharder** [comment]
Fixed

**Pull request merged**
