### PR TITLE
baselayout: Switch to ypkg format

### PR DESCRIPTION
**Pull request by joebonrichie**
**Summary**

- Comar stuff isn't needed and will be dropped in eopkg py3
- Use `permanent` so eopkg never deletes the paths

**Test Plan**

- Install this pkg and canonical baselayout to a new rootfs and confirm the directory layouts are the same
- Create a new rootfs from this package:
  ```
  $ sudo /usr/bin/eopkg it baselayout-1.9.0-76-1-x86_64.eopkg -D /tmp/baselayout-rootfs/
  $ sudo /usr/bin/eopkg ur -D /tmp/baselayout-rootfs
  $ sudo /usr/bin/eopkg --ignore-comar it -c system.base -D /tmp/baselayout-rootfs
  ```
- Chroot in to a new solus rootfs created from this package:
  `sudo systemd-nspawn -D /tmp/baselayout-rootfs -b`
- Install package to a VM, reboot, install and remove a few packages and confirm nothing blows up.
- Install package locally, install updates, confirm nothing blows up

**Packager's Note**
- CI expected to fail and it doesn't understand package conversions

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by ermo** [comment]
Try:

    # Setup symlinks
    ln -srv %installroot%/lib64 %installroot%/lib
    ln -srv %installroot%/usr/lib64 %installroot%/usr/lib
    ln -srv %installroot%/run %installroot/var/run
    ln -sv %installroot%/run/lock %installroot%/var/lock

**Comment by joebonrichie** [comment]
Tentatively marking as ready

**Comment by ermo** [comment]
> - Chroot in to a new solus rootfs created from this package

I experimented with doing a systemd-nspawn in instead with the following invocation:

    sudo systemd-nspawn -D /tmp/baselayout-rootfs/ -b

... and it worked.

I've updated the test plan with reproducible steps and a fixed rootfs location in /tmp

**Comment by ermo** [comment]
> **Test Plan**
> 
>     * Install this pkg and canonical baselayout to a new rootfs and confirm the directory layouts are the same
>     * Create a new rootfs from this package:
>       ```
>       $ sudo /usr/bin/eopkg it baselayout-1.9.0-76-1-x86_64.eopkg -D /tmp/baselayout-rootfs/
>       $ sudo /usr/bin/eopkg ur -D /tmp/baselayout-rootfs
>       $ sudo /usr/bin/eopkg --ignore-comar it -c system.base -D /tmp/baselayout-rootfs
>       ```
>     * Chroot in to a new solus rootfs created from this package:
>       `sudo systemd-nspawn -D /tmp/baselayout-rootfs -b`
>     * Install package to a VM, reboot, install and remove a few packages and confirm nothing blows up.
>     * Install package locally, install updates, confirm nothing blows up
>

I have just successfully completed the above Test Plan and am currently running my workstation off of the new baselayout from this PR with no observed issues.

**Pull request merged**
