### PR TITLE
clj-kondo: Update to 2023.12.15

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Changelog can be found [here](https://github.com/clj-kondo/clj-kondo/blob/v2023.12.15/CHANGELOG.md)
- Added `homepage` key to `package.yml` (Part of #411)

**Test Plan**

- Run example command found in [README](https://github.com/clj-kondo/clj-kondo/blob/master/README.md)
- Make sure it behaves as expected
- Verified the added homepage loads information about the package

**Checklist**

- [x] Package was built and tested against unstable

**Note**

This is part of my homepage _mission_ . I see that it has new version and easy to test, so eeeh why not update it? Sorry @olymk2 if I step on your toes. You might wanna take a look at this. Cheers!

### CODE REVIEW

**Comment by algent-al** [comment]
Hey @olymk2, can you take a look at this PR please.

**Comment by olymk2** [comment]
@malfisya no problem at all I am not precious about who changes the packages :)

@algent-al check looks good, sorry not great with notification I manually check github for updates as email was just to noisy so I tuned them off.

**Review by algent-al — CHANGES_REQUESTED** [review]
Let's listen the bot :D

Builddeps are not in order.

**Comment by olymk2** [comment]
> Let's listen the bot :D
> 
> Builddeps are not in order.

Sure I will let @malfisya sort that as he last modified it, out of interest does this effect anything I noticed it picked it up but thought the order would make no difference as long as they exist or is this not the case ?

**Comment by algent-al** [comment]
> > Let's listen the bot :D
> > 
> > Builddeps are not in order.
> 
> Sure I will let @malfisya sort that as he last modified it, out of interest does this effect anything I noticed it picked it up but thought the order would make no difference as long as they exist or is this not the case ?

No worries, it doesn't affect anything. It is just to have things organised.

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
