### PR TITLE
Add sync notes checkbox to PR template

### PR DESCRIPTION
**Pull request by sheepman4267**
**Summary**

This adds an item to the checklist prompting maintainers to let us know if they think the change should be mentioned in the sync notes. As suggested by @ReillyBrogan in matrix.

**Test Plan**

N/A, this is a change to github configuration.

**Checklist**

- [ ] Package was built and tested against unstable

### CODE REVIEW

**Review by ermo — COMMENTED** [review]
Maybe consider replacing "should" with "could gainfully" to indicate that the contributor is suggesting that there are gotchas or notable changes that warrant highlighting for the sake of users?

**Comment by malfisya** [comment]
Is is possible to parse this in worklog.py? That would be wonderful.

**Comment by sheepman4267** [comment]
> Maybe consider replacing "should" with "could gainfully" to indicate that the contributor is suggesting that there are gotchas or notable changes that warrant highlighting for the sake of users?

Good call. Done!

**Review by ermo — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
