### PR TITLE
Update libgit2 to 1.8.1 & rebuilds and misc. updates

### PR DESCRIPTION
**Pull request by joebonrichie**
**Summary**

Update libgit2 to 1.8.1
Update libgit2-glib to 1.2.0
Update horizon-eda to 2.6.0
Deprecate podofo-09

**Test Plan**

To be tested after sync

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
I went through this and made the following changes:
- Fixed builddep order
- Switched libgit2 to use pcre2 instead
- Added a manual rundep for libgit2-devel on libssh2-devel since `-lssh` is part of the link flags
- Added monitoring.yml to all packages
- Switched zed and eza to use the system libgit2 (eza needed an update to pick up a newer git2 crate which was done on main)

**Comment by ReillyBrogan** [comment]
- Added nushell

**Review by ReillyBrogan — APPROVED** [review]
Wow! Somehow all of the issues I had have already been resolved in this PR!

**Comment by joebonrichie** [comment]
horizon-eda just closes (without a segfault) when cloning the default horizon pool so holding off for now

**Comment by ReillyBrogan** [comment]
> horizon-eda just closes (without a segfault) when cloning the default horizon pool so holding off for now

Given that this is pre-existing behavior I don't think it should block this PR

**Pull request merged**
