### PR TITLE
signal-desktop: Update to 7.3.1

### PR DESCRIPTION
**Pull request by kmarud**
**Summary**

Release note
- [7.3.1](https://github.com/signalapp/Signal-Desktop/releases/tag/v7.3.1)

**Test Plan**
- Logged in into app
- Verified if contacts was synchronized
- Sent somme messages

**Checklist**
- [x] Package was build and tested against unstable

### CODE REVIEW

**Comment by kmarud** [comment]
Resolves issue [1962](https://github.com/getsolus/packages/issues/1962)

**Comment by HarveyDevel** [comment]
Thank you for your efforts, but the reason the maintainer has not updated this package is due to a breakage in our package history for `signal-desktop` until that is resolved we are unable to update this package.

Additionally when a package has a dedicated maintainer indicated by the presence of a MAINTAINERS.md it should be left to them to maintain. A update request can still be submitted (as you did) should you believe an update is important and has been overlooked.

**Comment by kmarud** [comment]
> Thank you for your efforts, but the reason the maintainer has not updated this package is due to a breakage in our package history for `signal-desktop` until that is resolved we are unable to update this package.
> 
> Additionally when a package has a dedicated maintainer indicated by the presence of a MAINTAINERS.md it should be left to them to maintain. A update request can still be submitted (as you did) should you believe an update is important and has been overlooked.

Hello Troy,
I didn't notice that, so if there is MAINTAINERS.md file inside the package, it means that someone is already taking care of it, right? 
I had no issue with building this package so it was double surprising it hadn't been updated yet.

Regards,
Kamil

**Comment by HarveyDevel** [comment]
> Hello Troy, I didn't notice that, so if there is MAINTAINERS.md file inside the package, it means that someone is already taking care of it, right?

Hello. Yep as you can see here https://github.com/getsolus/packages/tree/main/packages/s/signal-desktop the package has a MAINTAINERS.md file and the person listed inside that file is the dedicated maintainer.

>  I had no issue with building this package so it was double surprising it hadn't been updated yet.

That is because when built locally the package history is not generated, when built on the build server for inclusion in the repository it is. Once we have moved ypkg & eopkg to python3 **or** add a workaround to solbuild the issue will be resolved and the package updated.

**Pull request closed without merging**
