### PR TITLE
ROCm v6.2.4

### PR DESCRIPTION
**Pull request by GZGavinZhao**
- **rocm-llvm: Update to v6.2.4**
- **hsakmt: Update to v6.2.4**
- **rocm-cmake: Update to v6.2.4**
- **rocm-device-libs: Update to v6.2.4**
- **rocm-compilersupport: Update to v6.2.4**
- **fixup! rocm-compilersupport: Update to v6.2.4**
- **rocm-runtime: Update to v6.2.4**
- **hsa-amd-aqlprofile: update to v6.2.0**
- **rocm-core: Update to v6.2.4**
- **rocprofiler-register: Add at v6.2.4**

**Summary**

Updated the ROCm stack to v6.2.4 and PyTorch to v2.5, bringing performance and compatibility improvements to ML workflows on Solus.

**Test Plan**

- [x] Stable Diffusion works on `gfx1032`
- [x] Stable Diffusion works on `gfx900`
- [x] Anime4KCPP works on `gfx1032` (OpenCL)
- [x] Anime4KCPP works on `gfx90c` (OpenCL)
- [x] Anime4KCPP works on `gfx900` (OpenCL)
- [x] `llama.cpp` works on `gfx1032`
- [x] `llama.cpp` works on `gfx90c`
- [x] `llama.cpp` works on `gfx900`
- [x] `gfx1030` code runs on `gfx1032`
- [x] `gfx900` code runs on `gfx90c`
- [x] ~~pytorch/examples passed on `gfx1032`~~ (upstream issue pytorch/pytorch#143728)
- [x] ~~pytorch/examples passed on `gfx90c`~~ (upstream issue pytorch/pytorch#143728)
- [x] ~~pytorch/examples passed on `gfx900`~~ (upstream issue pytorch/pytorch#143728)

**Checklist**

- [x] Package was built and tested against unstable
- [x] This change could gainfully be listed in the weekly sync notes once merged (Write an appropriate message in the Summary section)

### CODE REVIEW

**Comment by GZGavinZhao** [comment]
Everything has been packaged. Just tests pending.

**Comment by GZGavinZhao** [comment]
Last rebuild of the entire stack to make sure everything builds in the expected order. Will merge after this finishes.

**Comment by GZGavinZhao** [comment]
Done, will merge and publish after sync.

**Comment by HarveyDevel** [comment]
> Done, will merge and publish after sync.

No sync this week due to holidays.

**Pull request merged**
