### PR TITLE
ci: Render commits as comments

### PR DESCRIPTION
**Pull request by silkeh**
**Summary**

Render commits as notice messages in the diff.

**Test Plan**

See [this test PR](https://github.com/silkeh/packages/pull/3).

**Checklist**

- [x] ~~Package was built and tested against unstable~~ n/a

### CODE REVIEW

**Comment by silkeh** [comment]
This does not actually render the markdown :cry: 

afbeelding

**Comment by ReillyBrogan** [comment]
That's unfortunate. Perhaps something like [this](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) might work better? Or perhaps we could have the action create a comment or add something to the summary at the bottom of the discussion page?

**Comment by silkeh** [comment]
@ReillyBrogan: good idea, that looks much nicer. See [this summary](https://github.com/silkeh/packages/actions/runs/6472994724) (with too many entries as my fork lags behind this branch).

We'll have to change the default commit template to use `**` over `##`, but that might make life easier with Git anyway.

**Review by ReillyBrogan — APPROVED** [review]
LGTM

**Pull request merged**
