### PR TITLE
neovim: Update to 0.9.2

### PR DESCRIPTION
**Pull request by EbonJaeger**
**Summary**

- libuv: Update to 1.46.0
- libluv: Update to 1.45.0
- libvterm: Update to 0.3.2
- neovim: Update to 0.9.2
- neovim-qt: Safety rebuild for neovim
- python-neovim: Add homepage to package

**Test Plan**

Open a file with `nvim`, insert and delete text, and save the file.

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by davidjharder — APPROVED** [review]
LGTM. Do you want to merge and publish? I assume this has to be built in the order of your commits?

**Comment by EbonJaeger** [comment]
Doesn't matter to me. I still haven't gotten an answer on how pushing stacks to the build server works now, though, soo :shrug:

**Comment by joebonrichie** [comment]
Unfortunately you still have to publish each package manually in the right order after merging.

e.g. `gotopkg foo; go-task publish; go-task notify-complete && gotopkg bar; go-task publish; go-task notify-complete` etc.

**Comment by joebonrichie** [comment]
Ah did you squash merge this? Can only squash merge single package updates.

**Pull request merged**
