### PR TITLE
ci: Add PR and Python linters

### PR DESCRIPTION
**Pull request by silkeh**
**Summary**

This PR adds some initial linters for for pull requests. Checks are mostly focussed on common packaging mistakes:

- `homepage` not set
- Incorrect directory
- `patch <` instead of `patch -i`
- Various unwanted files (including in incorrect directories)
- Inconsistent `package.yml` and `pspec_x86_64.yml`.

**Test Plan**

This PR!

**Checklist**

- [ ] ~~Package was built and tested against unstable~~ n/a

### CODE REVIEW

**Comment by silkeh** [comment]
In action:

Screenshot 2023-09-23 at 16-11-59 Test ci Add CI checks for PRs by silkeh · Pull Request #1 · silkeh_packages

**Review by ReillyBrogan — CHANGES_REQUESTED** [review]
Can you add go-task support for running these linters locally? IE, someone should be able to identify that their PR will pass the linter tests _before_ they push it.

**Comment by silkeh** [comment]
@ReillyBrogan: I have added the go-task files, please let me know if it's sufficient!

**Comment by ReillyBrogan** [comment]
I checked out this branch locally, ran `go-task check` in the `packages/r/rssguard` directory and got the following output:
```
task: [check] /home/reilly/Solus/packages/common/CI/package_checks.py --ref origin/main..HEAD 
Checking files: .flake8, .github/workflows/package_lint.yml, .github/workflows/script_lint.yml, common/CI/package_checks.py, common/Scripts/rebuild-template-script.sh, common/Taskfile.yml, packages/0/0ad-data/package.yml, packages/0/0ad-data/pspec_x86_64.xml, packages/a/akonadi-calendar/abi_libs, packages/a/akonadi-calendar/abi_symbols, packages/a/akonadi-calendar/abi_used_libs, packages/a/akonadi-calendar/abi_used_symbols, packages/a/akonadi-calendar/package.yml, packages/a/akonadi-calendar/pspec_x86_64.xml, packages/a/akonadi-contacts/abi_libs, packages/a/akonadi-contacts/abi_symbols, packages/a/akonadi-contacts/abi_used_libs, packages/a/akonadi-contacts/abi_used_symbols, packages/a/akonadi-contacts/package.yml, packages/a/akonadi-contacts/pspec_x86_64.xml, packages/a/akonadi-import-wizard/abi_symbols, packages/a/akonadi-import-wizard/abi_used_libs, packages/a/akonadi-import-wizard/abi_used_symbols, packages/a/akonadi-import-wizard/package.yml, packages/a/akonadi-import-wizard/pspec_x86_64.xml, packages/a/akonadi-mime/abi_symbols, packages/a/akonadi-mime/abi_used_symbols, packages/a/akonadi-mime/package.yml, packages/a/akonadi-mime/pspec_x86_64.xml, packages/a/akonadi-notes/package.yml, packages/a/akonadi-notes/pspec_x86_64.xml, packages/a/akonadi-search/abi_symbols, packages/a/akonadi-search/abi_used_symbols, packages/a/akonadi-search/package.yml, packages/a/akonadi-search/pspec_x86_64.xml, packages/a/akonadi/abi_libs, packages/a/akonadi/abi_symbols, packages/a/akonadi/abi_used_libs, packages/a/akonadi/abi_used_symbols, packages/a/akonadi/package.yml, packages/a/akonadi/pspec_x86_64.xml, packages/a/akonadiconsole/abi_used_libs, packages/a/akonadiconsole/abi_used_symbols, packages/a/akonadiconsole/package.yml, packages/a/akonadiconsole/pspec_x86_64.xml, packages/a/akregator/abi_symbols, packages/a/akregator/abi_used_libs, packages/a/akregator/abi_used_symbols, packages/a/akregator/package.yml, packages/a/akregator/pspec_x86_64.xml, packages/a/alacritty/package.yml, packages/a/alacritty/pspec_x86_64.xml, packages/a/amule/abi_used_symbols, packages/a/amule/package.yml, packages/a/amule/pspec_x86_64.xml, packages/a/ark/abi_used_libs, packages/a/ark/abi_used_symbols, packages/a/ark/package.yml, packages/a/ark/pspec_x86_64.xml, packages/b/baloo-widgets/abi_used_symbols, packages/b/baloo-widgets/package.yml, packages/b/baloo-widgets/pspec_x86_64.xml, packages/b/bdwgc/package.yml, packages/b/bdwgc/pspec_x86_64.xml, packages/b/bitwarden-desktop/files/Bitwarden.desktop, packages/b/bitwarden-desktop/package.yml, packages/b/bitwarden-desktop/pspec_x86_64.xml, packages/b/blinken/package.yml, packages/b/blinken/pspec_x86_64.xml, packages/b/bovo/package.yml, packages/b/bovo/pspec_x86_64.xml, packages/b/brave/package.yml, packages/b/brave/pspec_x86_64.xml, packages/b/budgie-desktop/abi_symbols, packages/b/budgie-desktop/abi_used_symbols, packages/b/budgie-desktop/files/0001-Add-xdg-desktop-portal-config-443.patch, packages/b/budgie-desktop/files/0001-Work-around-more-SN-dbusmenu-quirks.patch, packages/b/budgie-desktop/package.yml, packages/b/budgie-desktop/pspec_x86_64.xml, packages/c/calendarsupport/abi_symbols, packages/c/calendarsupport/abi_used_symbols, packages/c/calendarsupport/package.yml, packages/c/calendarsupport/pspec_x86_64.xml, packages/c/cockatrice/abi_used_symbols, packages/c/cockatrice/package.yml, packages/c/cockatrice/pspec_x86_64.xml, packages/c/colord-kde/package.yml, packages/c/colord-kde/pspec_x86_64.xml, packages/c/cutter/abi_symbols, packages/c/cutter/abi_used_libs, packages/c/cutter/abi_used_symbols, packages/c/cutter/package.yml, packages/c/cutter/pspec_x86_64.xml, packages/d/dav1d/package.yml, packages/d/dav1d/pspec_x86_64.xml, packages/d/dejavu-fonts-ttf/package.yml, packages/d/dejavu-fonts-ttf/pspec_x86_64.xml, packages/d/discord/package.yml, packages/d/discord/pspec_x86_64.xml, packages/d/dolphin-plugins/package.yml, packages/d/dolphin-plugins/pspec_x86_64.xml, packages/d/dolphin/abi_symbols, packages/d/dolphin/abi_used_symbols, packages/d/dolphin/package.yml, packages/d/dolphin/pspec_x86_64.xml, packages/e/elisa/abi_symbols, packages/e/elisa/abi_used_symbols, packages/e/elisa/package.yml, packages/e/elisa/pspec_x86_64.xml, packages/e/eventviews/abi_symbols, packages/e/eventviews/abi_used_symbols, packages/e/eventviews/package.yml, packages/e/eventviews/pspec_x86_64.xml, packages/e/eza/abi_used_symbols, packages/e/eza/package.yml, packages/e/eza/pspec_x86_64.xml, packages/f/falkon/abi_symbols, packages/f/falkon/abi_used_libs, packages/f/falkon/abi_used_symbols, packages/f/falkon/package.yml, packages/f/falkon/pspec_x86_64.xml, packages/f/ffmpegthumbs/abi_symbols, packages/f/ffmpegthumbs/abi_used_libs, packages/f/ffmpegthumbs/abi_used_symbols, packages/f/ffmpegthumbs/package.yml, packages/f/ffmpegthumbs/pspec_x86_64.xml, packages/f/fftw/package.yml, packages/f/fftw/pspec_x86_64.xml, packages/f/filelight/abi_used_symbols, packages/f/filelight/package.yml, packages/f/filelight/pspec_x86_64.xml, packages/f/font-awesome-ttf/package.yml, packages/f/font-awesome-ttf/pspec_x86_64.xml, packages/g/ghostwriter/abi_used_symbols, packages/g/ghostwriter/package.yml, packages/g/ghostwriter/pspec_x86_64.xml, packages/g/glibc/package.yml, packages/g/glibc/pspec_x86_64.xml, packages/g/grantleetheme/abi_symbols, packages/g/grantleetheme/package.yml, packages/g/grantleetheme/pspec_x86_64.xml, packages/g/gwenview/abi_symbols, packages/g/gwenview/abi_used_symbols, packages/g/gwenview/package.yml, packages/g/gwenview/pspec_x86_64.xml, packages/h/hunspell-it/package.yml, packages/h/hunspell-it/pspec_x86_64.xml, packages/h/hwdata/package.yml, packages/h/hwdata/pspec_x86_64.xml, packages/i/incidenceeditor/abi_symbols, packages/i/incidenceeditor/abi_used_libs, packages/i/incidenceeditor/abi_used_symbols, packages/i/incidenceeditor/package.yml, packages/i/incidenceeditor/pspec_x86_64.xml, packages/k/k3b/abi_symbols, packages/k/k3b/abi_used_libs, packages/k/k3b/abi_used_symbols, packages/k/k3b/package.yml, packages/k/k3b/pspec_x86_64.xml, packages/k/kaccounts-integration/abi_used_symbols, packages/k/kaccounts-integration/package.yml, packages/k/kaccounts-integration/pspec_x86_64.xml, packages/k/kaccounts-providers/package.yml, packages/k/kaccounts-providers/pspec_x86_64.xml, packages/k/kaddressbook/abi_symbols, packages/k/kaddressbook/abi_used_libs, packages/k/kaddressbook/abi_used_symbols, packages/k/kaddressbook/package.yml, packages/k/kaddressbook/pspec_x86_64.xml, packages/k/kalzium/package.yml, packages/k/kalzium/pspec_x86_64.xml, packages/k/kamera/abi_used_symbols, packages/k/kamera/package.yml, packages/k/kamera/pspec_x86_64.xml, packages/k/kanagram/package.yml, packages/k/kanagram/pspec_x86_64.xml, packages/k/kate/abi_libs, packages/k/kate/abi_symbols, packages/k/kate/abi_used_symbols, packages/k/kate/package.yml, packages/k/kate/pspec_x86_64.xml, packages/k/kbackup/package.yml, packages/k/kbackup/pspec_x86_64.xml, packages/k/kcachegrind/abi_used_symbols, packages/k/kcachegrind/package.yml, packages/k/kcachegrind/pspec_x86_64.xml, packages/k/kcalc/package.yml, packages/k/kcalc/pspec_x86_64.xml, packages/k/kcalutils/abi_symbols, packages/k/kcalutils/abi_used_libs, packages/k/kcalutils/abi_used_symbols, packages/k/kcalutils/package.yml, packages/k/kcalutils/pspec_x86_64.xml, packages/k/kcharselect/package.yml, packages/k/kcharselect/pspec_x86_64.xml, packages/k/kcolorchooser/package.yml, packages/k/kcolorchooser/pspec_x86_64.xml, packages/k/kdebugsettings/abi_libs, packages/k/kdebugsettings/abi_symbols, packages/k/kdebugsettings/abi_used_libs, packages/k/kdebugsettings/abi_used_symbols, packages/k/kdebugsettings/package.yml, packages/k/kdebugsettings/pspec_x86_64.xml, packages/k/kdeconnect/abi_symbols, packages/k/kdeconnect/abi_used_libs, packages/k/kdeconnect/abi_used_symbols, packages/k/kdeconnect/package.yml, packages/k/kdeconnect/pspec_x86_64.xml, packages/k/kdegraphics-mobipocket/package.yml, packages/k/kdegraphics-mobipocket/pspec_x86_64.xml, packages/k/kdegraphics-thumbnailers/package.yml, packages/k/kdegraphics-thumbnailers/pspec_x86_64.xml, packages/k/kdenetwork-filesharing/abi_used_symbols, packages/k/kdenetwork-filesharing/package.yml, packages/k/kdenetwork-filesharing/pspec_x86_64.xml, packages/k/kdenlive/abi_used_symbols, packages/k/kdenlive/package.yml, packages/k/kdenlive/pspec_x86_64.xml, packages/k/kdepim-addons/abi_used_libs, packages/k/kdepim-addons/abi_used_symbols, packages/k/kdepim-addons/package.yml, packages/k/kdepim-addons/pspec_x86_64.xml, packages/k/kdepim-runtime/abi_libs, packages/k/kdepim-runtime/abi_symbols, packages/k/kdepim-runtime/abi_used_libs, packages/k/kdepim-runtime/abi_used_symbols, packages/k/kdepim-runtime/package.yml, packages/k/kdepim-runtime/pspec_x86_64.xml, packages/k/kdev-php/abi_symbols, packages/k/kdev-php/abi_used_libs, packages/k/kdev-php/abi_used_symbols, packages/k/kdev-php/package.yml, packages/k/kdev-php/pspec_x86_64.xml, packages/k/kdevelop/abi_libs, packages/k/kdevelop/abi_symbols, packages/k/kdevelop/abi_used_symbols, packages/k/kdevelop/files/cb362b799f07b1d73c3674cb380bddec1ee2a600.patch, packages/k/kdevelop/package.yml, packages/k/kdevelop/pspec_x86_64.xml, packages/k/kdialog/abi_used_symbols, packages/k/kdialog/package.yml, packages/k/kdialog/pspec_x86_64.xml, packages/k/kfind/package.yml, packages/k/kfind/pspec_x86_64.xml, packages/k/kgeography/package.yml, packages/k/kgeography/pspec_x86_64.xml, packages/k/kget/abi_symbols, packages/k/kget/abi_used_symbols, packages/k/kget/package.yml, packages/k/kget/pspec_x86_64.xml, packages/k/kgpg/abi_used_libs, packages/k/kgpg/abi_used_symbols, packages/k/kgpg/package.yml, packages/k/kgpg/pspec_x86_64.xml, packages/k/kidentitymanagement/abi_symbols, packages/k/kidentitymanagement/package.yml, packages/k/kidentitymanagement/pspec_x86_64.xml, packages/k/kimap/package.yml, packages/k/kimap/pspec_x86_64.xml, packages/k/kio-extras/abi_libs, packages/k/kio-extras/abi_symbols, packages/k/kio-extras/abi_used_symbols, packages/k/kio-extras/package.yml, packages/k/kio-extras/pspec_x86_64.xml, packages/k/kio-gdrive/package.yml, packages/k/kio-gdrive/pspec_x86_64.xml, packages/k/kirigami-addons/abi_libs, packages/k/kirigami-addons/abi_symbols, packages/k/kirigami-addons/abi_used_symbols, packages/k/kirigami-addons/package.yml, packages/k/kirigami-addons/pspec_x86_64.xml, packages/k/kitinerary/abi_symbols, packages/k/kitinerary/abi_used_libs, packages/k/kitinerary/abi_used_symbols, packages/k/kitinerary/package.yml, packages/k/kitinerary/pspec_x86_64.xml, packages/k/kldap/abi_symbols, packages/k/kldap/abi_used_symbols, packages/k/kldap/package.yml, packages/k/kldap/pspec_x86_64.xml, packages/k/kleopatra/abi_used_libs, packages/k/kleopatra/abi_used_symbols, packages/k/kleopatra/package.yml, packages/k/kleopatra/pspec_x86_64.xml, packages/k/kmag/package.yml, packages/k/kmag/pspec_x86_64.xml, packages/k/kmahjongg/package.yml, packages/k/kmahjongg/pspec_x86_64.xml, packages/k/kmail-account-wizard/abi_used_libs, packages/k/kmail-account-wizard/abi_used_symbols, packages/k/kmail-account-wizard/package.yml, packages/k/kmail-account-wizard/pspec_x86_64.xml, packages/k/kmail/abi_symbols, packages/k/kmail/abi_used_libs, packages/k/kmail/abi_used_symbols, packages/k/kmail/package.yml, packages/k/kmail/pspec_x86_64.xml, packages/k/kmailtransport/abi_libs, packages/k/kmailtransport/abi_symbols, packages/k/kmailtransport/abi_used_libs, packages/k/kmailtransport/abi_used_symbols, packages/k/kmailtransport/package.yml, packages/k/kmailtransport/pspec_x86_64.xml, packages/k/kmbox/package.yml, packages/k/kmbox/pspec_x86_64.xml, packages/k/kmime/package.yml, packages/k/kmime/pspec_x86_64.xml, packages/k/kmix/abi_symbols, packages/k/kmix/abi_used_libs, packages/k/kmix/abi_used_symbols, packages/k/kmix/package.yml, packages/k/kmix/pspec_x86_64.xml, packages/k/knotes/abi_used_libs, packages/k/knotes/abi_used_symbols, packages/k/knotes/package.yml, packages/k/knotes/pspec_x86_64.xml, packages/k/kolourpaint/abi_used_symbols, packages/k/kolourpaint/package.yml, packages/k/kolourpaint/pspec_x86_64.xml, packages/k/kompare/abi_used_symbols, packages/k/kompare/package.yml, packages/k/kompare/pspec_x86_64.xml, packages/k/konsole/abi_symbols, packages/k/konsole/abi_used_symbols, packages/k/konsole/package.yml, packages/k/konsole/pspec_x86_64.xml, packages/k/kontact/abi_used_libs, packages/k/kontact/abi_used_symbols, packages/k/kontact/package.yml, packages/k/kontact/pspec_x86_64.xml, packages/k/kontactinterface/abi_symbols, packages/k/kontactinterface/package.yml, packages/k/kontactinterface/pspec_x86_64.xml, packages/k/konversation/abi_symbols, packages/k/konversation/abi_used_symbols, packages/k/konversation/package.yml, packages/k/konversation/pspec_x86_64.xml, packages/k/korganizer/abi_symbols, packages/k/korganizer/abi_used_libs, packages/k/korganizer/abi_used_symbols, packages/k/korganizer/package.yml, packages/k/korganizer/pspec_x86_64.xml, packages/k/kpat/package.yml, packages/k/kpat/pspec_x86_64.xml, packages/k/kpimtextedit/abi_symbols, packages/k/kpimtextedit/abi_used_symbols, packages/k/kpimtextedit/package.yml, packages/k/kpimtextedit/pspec_x86_64.xml, packages/k/kpkpass/abi_used_symbols, packages/k/kpkpass/package.yml, packages/k/kpkpass/pspec_x86_64.xml, packages/k/kpmcore/abi_used_symbols, packages/k/kpmcore/package.yml, packages/k/kpmcore/pspec_x86_64.xml, packages/k/krdc/package.yml, packages/k/krdc/pspec_x86_64.xml, packages/k/krfb/abi_used_symbols, packages/k/krfb/package.yml, packages/k/krfb/pspec_x86_64.xml, packages/k/ksanecore/abi_used_symbols, packages/k/ksanecore/package.yml, packages/k/ksanecore/pspec_x86_64.xml, packages/k/kshisen/package.yml, packages/k/kshisen/pspec_x86_64.xml, packages/k/ksmtp/package.yml, packages/k/ksmtp/pspec_x86_64.xml, packages/k/ksystemlog/abi_used_libs, packages/k/ksystemlog/abi_used_symbols, packages/k/ksystemlog/package.yml, packages/k/ksystemlog/pspec_x86_64.xml, packages/k/kteatime/abi_used_libs, packages/k/kteatime/abi_used_symbols, packages/k/kteatime/package.yml, packages/k/kteatime/pspec_x86_64.xml, packages/k/ktnef/package.yml, packages/k/ktnef/pspec_x86_64.xml, packages/k/kwalletmanager/package.yml, packages/k/kwalletmanager/pspec_x86_64.xml, packages/k/kwave/package.yml, packages/k/kwave/pspec_x86_64.xml, packages/l/liberation-fonts-ttf/package.yml, packages/l/liberation-fonts-ttf/pspec_x86_64.xml, packages/l/libglu/abi_used_libs, packages/l/libglu/abi_used_libs32, packages/l/libglu/abi_used_symbols, packages/l/libglu/abi_used_symbols32, packages/l/libglu/package.yml, packages/l/libglu/pspec_x86_64.xml, packages/l/libgravatar/abi_symbols, packages/l/libgravatar/abi_used_libs, packages/l/libgravatar/abi_used_symbols, packages/l/libgravatar/package.yml, packages/l/libgravatar/pspec_x86_64.xml, packages/l/libkcddb/abi_symbols, packages/l/libkcddb/abi_used_symbols, packages/l/libkcddb/package.yml, packages/l/libkcddb/pspec_x86_64.xml, packages/l/libkdcraw/package.yml, packages/l/libkdcraw/pspec_x86_64.xml, packages/l/libkdegames/package.yml, packages/l/libkdegames/pspec_x86_64.xml, packages/l/libkdepim/abi_symbols, packages/l/libkdepim/abi_used_symbols, packages/l/libkdepim/package.yml, packages/l/libkdepim/pspec_x86_64.xml, packages/l/libkeduvocdocument/package.yml, packages/l/libkeduvocdocument/pspec_x86_64.xml, packages/l/libkexiv2/abi_used_symbols, packages/l/libkexiv2/package.yml, packages/l/libkexiv2/pspec_x86_64.xml, packages/l/libkgapi/abi_symbols, packages/l/libkgapi/package.yml, packages/l/libkgapi/pspec_x86_64.xml, packages/l/libkleo/abi_symbols, packages/l/libkleo/abi_used_libs, packages/l/libkleo/abi_used_symbols, packages/l/libkleo/package.yml, packages/l/libkleo/pspec_x86_64.xml, packages/l/libkmahjongg/package.yml, packages/l/libkmahjongg/pspec_x86_64.xml, packages/l/libkomparediff2/abi_symbols, packages/l/libkomparediff2/abi_used_symbols, packages/l/libkomparediff2/package.yml, packages/l/libkomparediff2/pspec_x86_64.xml, packages/l/libksane/package.yml, packages/l/libksane/pspec_x86_64.xml, packages/l/libksieve/abi_symbols, packages/l/libksieve/abi_used_libs, packages/l/libksieve/abi_used_symbols, packages/l/libksieve/package.yml, packages/l/libksieve/pspec_x86_64.xml, packages/l/libktorrent/package.yml, packages/l/libktorrent/pspec_x86_64.xml, packages/l/libluv/abi_used_symbols, packages/l/libluv/package.yml, packages/l/libluv/pspec_x86_64.xml, packages/l/librecad/package.yml, packages/l/librecad/pspec_x86_64.xml, packages/l/libuv/abi_symbols, packages/l/libuv/abi_used_symbols, packages/l/libuv/package.yml, packages/l/libuv/pspec_x86_64.xml, packages/l/libvterm/abi_symbols, packages/l/libvterm/package.yml, packages/l/libvterm/pspec_x86_64.xml, packages/l/libx11/package.yml, packages/l/libx11/pspec_x86_64.xml, packages/l/libxpm/abi_symbols, packages/l/libxpm/abi_symbols32, packages/l/libxpm/abi_used_symbols, packages/l/libxpm/abi_used_symbols32, packages/l/libxpm/package.yml, packages/l/libxpm/pspec_x86_64.xml, packages/l/lokalize/abi_used_symbols, packages/l/lokalize/package.yml, packages/l/lokalize/pspec_x86_64.xml, packages/m/mailcommon/abi_symbols, packages/m/mailcommon/abi_used_libs, packages/m/mailcommon/abi_used_symbols, packages/m/mailcommon/package.yml, packages/m/mailcommon/pspec_x86_64.xml, packages/m/mailimporter/abi_symbols, packages/m/mailimporter/abi_used_libs, packages/m/mailimporter/abi_used_symbols, packages/m/mailimporter/package.yml, packages/m/mailimporter/pspec_x86_64.xml, packages/m/man-pages/package.yml, packages/m/man-pages/pspec_x86_64.xml, packages/m/marble/abi_symbols, packages/m/marble/abi_used_symbols, packages/m/marble/package.yml, packages/m/marble/pspec_x86_64.xml, packages/m/marp-cli/package.yml, packages/m/marp-cli/pspec_x86_64.xml, packages/m/mesalib/abi_used_symbols, packages/m/mesalib/abi_used_symbols32, packages/m/mesalib/package.yml, packages/m/mesalib/pspec_x86_64.xml, packages/m/messagelib/abi_symbols, packages/m/messagelib/abi_used_libs, packages/m/messagelib/abi_used_symbols, packages/m/messagelib/package.yml, packages/m/messagelib/pspec_x86_64.xml, packages/m/minuet/abi_symbols, packages/m/minuet/package.yml, packages/m/minuet/pspec_x86_64.xml, packages/m/mpc-qt/package.yml, packages/m/mpc-qt/pspec_x86_64.xml, packages/n/neochat/abi_used_libs, packages/n/neochat/abi_used_symbols, packages/n/neochat/package.yml, packages/n/neochat/pspec_x86_64.xml, packages/n/neovim-qt/package.yml, packages/n/neovim-qt/pspec_x86_64.xml, packages/n/neovim/abi_symbols, packages/n/neovim/abi_used_symbols, packages/n/neovim/package.yml, packages/n/neovim/pspec_x86_64.xml, packages/n/neverball/abi_symbols, packages/n/neverball/package.yml, packages/n/neverball/pspec_x86_64.xml, packages/o/okular/abi_libs, packages/o/okular/abi_symbols, packages/o/okular/abi_used_libs, packages/o/okular/abi_used_symbols, packages/o/okular/package.yml, packages/o/okular/pspec_x86_64.xml, packages/o/openblas/abi_symbols, packages/o/openblas/abi_used_symbols, packages/o/openblas/package.yml, packages/o/openblas/pspec_x86_64.xml, packages/o/openssh/package.yml, packages/o/openssh/pspec_x86_64.xml, packages/p/packagekit/package.yml, packages/p/packagekit/pspec_x86_64.xml, packages/p/palapeli/package.yml, packages/p/palapeli/pspec_x86_64.xml, packages/p/paperwork/package.yml, packages/p/paperwork/pspec_x86_64.xml, packages/p/parley/abi_used_libs, packages/p/parley/abi_used_symbols, packages/p/parley/package.yml, packages/p/parley/pspec_x86_64.xml, packages/p/partitionmanager/package.yml, packages/p/partitionmanager/pspec_x86_64.xml, packages/p/pim-data-exporter/abi_used_libs, packages/p/pim-data-exporter/abi_used_symbols, packages/p/pim-data-exporter/package.yml, packages/p/pim-data-exporter/pspec_x86_64.xml, packages/p/pimcommon/abi_libs, packages/p/pimcommon/abi_symbols, packages/p/pimcommon/abi_used_symbols, packages/p/pimcommon/package.yml, packages/p/pimcommon/pspec_x86_64.xml, packages/p/ppsspp/package.yml, packages/p/ppsspp/pspec_x86_64.xml, packages/p/praat/MAINTAINERS.md, packages/p/praat/abi_used_symbols, packages/p/praat/package.yml, packages/p/praat/pspec_x86_64.xml, packages/p/print-manager/abi_symbols, packages/p/print-manager/abi_used_symbols, packages/p/print-manager/package.yml, packages/p/print-manager/pspec_x86_64.xml, packages/p/privoxy/abi_used_symbols, packages/p/privoxy/package.yml, packages/p/privoxy/pspec_x86_64.xml, packages/py/python-httplib2/package.yml, packages/py/python-httplib2/pspec_x86_64.xml, packages/py/python-humanize/package.yml, packages/py/python-humanize/pspec_x86_64.xml, packages/py/python-iniconfig/package.yml, packages/py/python-iniconfig/pspec_x86_64.xml, packages/py/python-injector/package.yml, packages/py/python-injector/pspec_x86_64.xml, packages/py/python-invoke/package.yml, packages/py/python-invoke/pspec_x86_64.xml, packages/py/python-ipdb/package.yml, packages/py/python-ipdb/pspec_x86_64.xml, packages/py/python-iso8601/package.yml, packages/py/python-iso8601/pspec_x86_64.xml, packages/py/python-isort/package.yml, packages/py/python-isort/pspec_x86_64.xml, packages/py/python-jaraco.classes/package.yml, packages/py/python-jaraco.classes/pspec_x86_64.xml, packages/py/python-jellyfish/abi_libs, packages/py/python-jellyfish/abi_symbols, packages/py/python-jellyfish/abi_used_libs, packages/py/python-jellyfish/abi_used_symbols, packages/py/python-jellyfish/package.yml, packages/py/python-jellyfish/pspec_x86_64.xml, packages/py/python-joblib/package.yml, packages/py/python-joblib/pspec_x86_64.xml, packages/py/python-keyring/package.yml, packages/py/python-keyring/pspec_x86_64.xml, packages/py/python-kiwisolver/abi_used_symbols, packages/py/python-kiwisolver/package.yml, packages/py/python-kiwisolver/pspec_x86_64.xml, packages/py/python-libevdev/MAINTAINERS.md, packages/py/python-libevdev/package.yml, packages/py/python-libevdev/pspec_x86_64.xml, packages/py/python-more-itertools/package.yml, packages/py/python-more-itertools/pspec_x86_64.xml, packages/py/python-neovim/package.yml, packages/py/python-neovim/pspec_x86_64.xml, packages/q/qemu/package.yml, packages/q/qemu/pspec_x86_64.xml, packages/q/qt5-base/package.yml, packages/q/qt5-base/pspec_x86_64.xml, packages/q/qt5-imageformats/package.yml, packages/q/qt5-imageformats/pspec_x86_64.xml, packages/q/qt5-location/abi_used_symbols, packages/q/qt5-location/package.yml, packages/q/qt5-location/pspec_x86_64.xml, packages/q/qt5-wayland/package.yml, packages/q/qt5-wayland/pspec_x86_64.xml, packages/r/rapidfuzz-cpp/package.yml, packages/r/rapidfuzz-cpp/pspec_x86_64.xml, packages/r/retroarch/package.yml, packages/r/retroarch/pspec_x86_64.xml, packages/r/rssguard/abi_symbols, packages/r/rssguard/abi_used_symbols, packages/r/rssguard/package.yml, packages/r/rssguard/pspec_x86_64.xml, packages/s/sdl2/package.yml, packages/s/sdl2/pspec_x86_64.xml, packages/s/signon-kwallet-extension/package.yml, packages/s/signon-kwallet-extension/pspec_x86_64.xml, packages/s/skanlite/package.yml, packages/s/skanlite/pspec_x86_64.xml, packages/s/sof-firmware/package.yml, packages/s/sof-firmware/pspec_x86_64.xml, packages/s/spectacle/abi_used_symbols, packages/s/spectacle/package.yml, packages/s/spectacle/pspec_x86_64.xml, packages/s/starfighter/package.yml, packages/s/starfighter/pspec_x86_64.xml, packages/s/streamlink/package.yml, packages/s/streamlink/pspec_x86_64.xml, packages/s/syncthing/package.yml, packages/s/syncthing/pspec_x86_64.xml, packages/s/systemd/package.yml, packages/s/systemd/pspec_x86_64.xml, packages/t/tailscale/package.yml, packages/t/tailscale/pspec_x86_64.xml, packages/u/ulauncher/package.yml, packages/u/ulauncher/pspec_x86_64.xml, packages/u/umbrello/package.yml, packages/u/umbrello/pspec_x86_64.xml, packages/v/veracrypt/abi_used_libs, packages/v/veracrypt/abi_used_symbols, packages/v/veracrypt/package.yml, packages/v/veracrypt/pspec_x86_64.xml, packages/v/vivaldi-snapshot/abi_symbols, packages/v/vivaldi-snapshot/abi_used_symbols, packages/v/vivaldi-snapshot/package.yml, packages/v/vivaldi-snapshot/pspec_x86_64.xml, packages/v/vivaldi-stable/package.yml, packages/v/vivaldi-stable/pspec_x86_64.xml, packages/v/vscode/files/product.json, packages/v/vscode/package.yml, packages/v/vscode/pspec_x86_64.xml, packages/y/yakuake/abi_used_libs, packages/y/yakuake/abi_used_symbols, packages/y/yakuake/package.yml, packages/y/yakuake/pspec_x86_64.xml, packages/z/zanshin/package.yml, packages/z/zanshin/pspec_x86_64.xml, packages/z/zotero/abi_used_symbols, packages/z/zotero/package.yml, packages/z/zotero/pspec_x86_64.xml
Traceback (most recent call last):
  File "/home/reilly/Solus/packages/common/CI/package_checks.py", line 205, in <module>
    run_checks(args.filename)
  File "/home/reilly/Solus/packages/common/CI/package_checks.py", line 164, in run_checks
    results = [result for check in checks for result in check.run(files)]
  File "/home/reilly/Solus/packages/common/CI/package_checks.py", line 164, in <listcomp>
    results = [result for check in checks for result in check.run(files)]
  File "/home/reilly/Solus/packages/common/CI/package_checks.py", line 62, in run
    return [Result(self._error, f, None, self._level)
  File "/home/reilly/Solus/packages/common/CI/package_checks.py", line 64, in <listcomp>
    if not self._includes_homepage(f)]
  File "/home/reilly/Solus/packages/common/CI/package_checks.py", line 68, in _includes_homepage
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'packages/0/0ad-data/package.yml'
```

**Comment by silkeh** [comment]
@ReillyBrogan: sorry about that, keeping track of paths was a mess. Should be fixed now!

**Comment by ReillyBrogan** [comment]
I checked your branch out, ran `task check`, and got a bunch of results that appeared to be from commits in main that were not in your branch. This seems incorrect to me, we should probably only be scanning files modified in commits on the local branch that are not in the default branch, not the other way around. The person submitting the PR receiving a bunch of errors on files that they haven't modified seems like bad UX to me.

**Comment by silkeh** [comment]
Agreed. Seems a simple diff was a bit naive. I have updated it to do a comparison since the merge base.

**Comment by ReillyBrogan** [comment]
Seems much better now, my only remaining nit is that it doesn't seem to be considering dirty state. I removed the homepage from a package.yml locally, ran `task check` and it succeeded. It did not fail until I made a test commit with that change.

**Comment by silkeh** [comment]
Yeah, the current version only tracks actually committed files. I can add a `--dirty` flag that adds uncommitted files (and add that by default in the go-task), but I would prefer doing that in a separate PR if you don't mind :slightly_smiling_face:.

**Review by ReillyBrogan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
