### PR TITLE
jabref: Update to v5.13

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Full changelog can be found [here](https://raw.githubusercontent.com/JabRef/jabref/v5.13/CHANGELOG.md)
- Add `homepage` key to `package.yml` (Part of getsolus/packages#411)
- Add appstream metainfo (Part of getsolus/packages#1389)
- Add monitoring.yml

**Test Plan**

TBD

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by davidjharder** [comment]
Does this launch for  you? I get errors + no launch.

**Comment by malfisya** [comment]
No, it doesn't launch for me either. I am still trying to figure it out.

**Comment by malfisya** [comment]
Launch error log:

```
 $ jabref                                                                                                                 
Messages are not initialized before accessing key: Display help on command line options
2024-07-24 06:08:00 [main] sun.util.logging.internal.LoggingProviderImpl$JULWrapper.log()
INFO: Created user preferences directory.
2024-07-24 06:08:00 [main] org.jabref.migrations.PreferencesMigrations.upgradeStoredBibEntryTypes()
INFO: Migrating old custom entry types.
2024-07-24 06:08:00 [main] org.jabref.Launcher.main()
ERROR: Unexpected exception: java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142)
	at java.base/java.nio.file.Path.of(Path.java:209)
	at org.jabref@5.13/org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist(TrustStoreManager.java:151)
	at org.jabref@5.13/org.jabref.Launcher.configureSSL(Launcher.java:202)
	at org.jabref@5.13/org.jabref.Launcher.main(Launcher.java:83)

```

**Comment by A108384** [comment]
I was able to get this to build and launch. I should have asked first, but I created a new PR referenced above. 

Is there a way that I should build on top of this one or what is the correct process for me to help with this?

**Comment by malfisya** [comment]
Nah, it is fine. You already make a new PR anyway. I don't feel like working on this anymore, so I will close this. Cheers!

**Pull request closed without merging**
