### PR TITLE
sfml: Update to 2.6.1

### PR DESCRIPTION
**Pull request by nelsontkq**
**Summary**

- Added `homepage` key and MAINTAINERS.md
- Removed xcb, libjpeg, and glew deps since they're no longer required (as noted in the changelong)
- [full SFML changelog](https://raw.githubusercontent.com/SFML/SFML/2.6.1/changelog.md)

**Test Plan**
- build and run the [cmake-sfml-project](https://github.com/SFML/cmake-sfml-project) template, and the sound example in the SFML git repo

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by ReillyBrogan — DISMISSED** [review]
You can probably split out the docs into a subpackage if you want the package to be leaner. Up to you, I'll merge this as soon as you respond if you don't want to do that.

**Review by ReillyBrogan — CHANGES_REQUESTED** [review]
Alright, so I actually noticed that I was wrong here. This upgrade of sfml changed the sonames of the libraries (note that `libsfml-*.so.2.5` in `abi_libs` is now `libsfml-*.so.2.6`), which means every package that was using those libs would stop working once this PR is landed. You'll need to do rebuilds for all of the following packages:
- `attract`
- `cendric`
- `dolphin-emu`
- `visualboyadvance-m`
- `witchblast`

Each rebuild will need to be added to this branch as a separate commit. If you've never done that before feel free to hop into Matrix and we can help you with it!

**Comment by nelsontkq** [comment]
@ReillyBrogan makes sense! I'll give it a go and contact if I need any help.

**Comment by nelsontkq** [comment]
@ReillyBrogan as discussed looks like minizip is causing `dolphin-emu` some bother.

If it's helpful to know, changing `pkgconfig(minizip-ng)` to `pkgconfig(minizip)` didn't fix the issue.

Here's the error message:
```
FAILED: Source/Core/UICommon/CMakeFiles/uicommon.dir/ResourcePack/ResourcePack.cpp.o 
/usr/bin/ccache /usr/lib64/ccache/bin/clang++ -DDATA_DIR=\"/usr/share/dolphin-emu/\" -DFMT_SHARED -DHAS_OPENGL -DHAS_VULKAN -DHAVE_EGL=1 -DHAVE_FFMPEG -DHAVE_LIBEVDEV=1 -DHAVE_LIBSYSTEMD -DHAVE_LIBUDEV=1 -DHAVE_LLVM -DHAVE_X11=1 -DHAVE_XRANDR=1 -DUSE_ANALYTICS=1 -DUSE_DISCORD_PRESENCE -DUSE_MEMORYWATCHER=1 -DUSE_PIPES=1 -DUSE_UPNP -D_ARCH_64=1 -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_M_X86=1 -D_M_X86_64=1 -D__LIBUSB__ -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Source/Core -I/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Externals/soundtouch -I/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Externals/discord-rpc/include -I/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Externals/picojson -I/home/build/YPKG/root/dolphin-emu/build/dolphin.git/solusBuildDir/Source/Core -I/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Externals/cpp-optparse/. -I/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Externals/Bochs_disasm -isystem /usr/include/minizip -isystem /usr/include/libusb-1.0 -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -fno-plt -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wall -Wno-error -Wp,-D_REENTRANT -flto=thin -Qunused-arguments -fcolor-diagnostics -O2 -g -DNDEBUG -std=c++20 -msse2 -fdiagnostics-color -fno-strict-aliasing -fno-exceptions -fvisibility-inlines-hidden -fvisibility=hidden -Wall -Wtype-limits -Wsign-compare -Wignored-qualifiers -Wuninitialized -Wshadow -Winit-self -Wmissing-declarations -Wmissing-variable-declarations -Werror=format -MD -MT Source/Core/UICommon/CMakeFiles/uicommon.dir/ResourcePack/ResourcePack.cpp.o -MF Source/Core/UICommon/CMakeFiles/uicommon.dir/ResourcePack/ResourcePack.cpp.o.d -o Source/Core/UICommon/CMakeFiles/uicommon.dir/ResourcePack/ResourcePack.cpp.o -c /home/build/YPKG/root/dolphin-emu/build/dolphin.git/Source/Core/UICommon/ResourcePack/ResourcePack.cpp
/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Source/Core/UICommon/ResourcePack/ResourcePack.cpp:39:7: error: no matching function for call to 'unzLocateFile'
  if (unzLocateFile(file, "manifest.json", nullptr) == UNZ_END_OF_LIST_OF_FILE)
      ^~~~~~~~~~~~~
/usr/include/minizip/mz_compat.h:364:17: note: candidate function not viable: no known conversion from 'std::nullptr_t' to 'unzFileNameCase' (aka 'int') for 3rd argument
ZEXPORT int     unzLocateFile(unzFile file, const char *filename, unzFileNameCase filename_case);
                ^
/home/build/YPKG/root/dolphin-emu/build/dolphin.git/Source/Core/UICommon/ResourcePack/ResourcePack.cpp:66:7: error: no matching function for call to 'unzLocateFile'
  if (unzLocateFile(file, "logo.png", nullptr) != UNZ_END_OF_LIST_OF_FILE)
      ^~~~~~~~~~~~~
/usr/include/minizip/mz_compat.h:364:17: note: candidate function not viable: no known conversion from 'std::nullptr_t' to 'unzFileNameCase' (aka 'int') for 3rd argument
ZEXPORT int     unzLocateFile(unzFile file, const char *filename, unzFileNameCase filename_case);
```

**Comment by nelsontkq** [comment]
Looks like the `witchblast` game relies on a few deprecated features in SFML. I pulled the repo to see if it's a quick fix and it looks like the game requires a few hundred changes. What are our options here? I guess we can package the old 2.5.* SFML library separately?

**Comment by ReillyBrogan** [comment]
Dolphin-emu: I just fixed the build failure in main (it comes from a changed API in minizip-ng 4.0.4). Rebase your branch on main, then build dolphin-emu again and it should work. Ref: 75d3376a44f1e06416f57b5593a671d9367e8329

Witchblast: Seems barely maintained upstream (and they're certainly not adding compat for new versions of libraries). We might as well remove it from the repos in that case, I certainly don't want to add a new version of SFML just to keep it building. Add a new commit deleting the `witchblast` package folder, and then open a PR [here](https://github.com/getsolus/solus-sc/pulls) with `witchblast` and `witchblast-dbginfo`, linked to this PR and that will get it taken care of (see other PRs in that repo for how it should look).

**Comment by nelsontkq** [comment]
@ReillyBrogan All done!

**Comment by ReillyBrogan** [comment]
We landed FFmpeg v6.1 a bit ago (in getsolus/packages#1380) and unfortunately that has led to conflicts on this branch. You'll need to rebase against main. If you're unfamiliar with that process, it will looks something like this:
1. Make sure to update your git remotes with `git fetch`
2. Assuming you have the official Solus repo as the `origin` remote then you would check out your branch and then run `git rebase origin/main` (adjust if you have the getsolus repo under a different remote name, though I generally recommend having getsolus/packages as `origin` while having your own fork as `nelson` or similar)
3. For each package that conflicts resolve the merge conflict, make sure to bump the package again so that it's whatever is in the main branch + 1.
4. Rebuild the package so that the ABI files and manifest is updated.
5. `git rebase --continue` to proceed to the next commit.

Note that while github is only showing `attract` and `visualboyadvance-m` as conflicting that is inaccurate. `dolphin-emu` will also need another bump, not sure why Github isn't showing it. 

Once you have things done you should be able to run `go-task check` in order to verify that you did things correctly. It will let you know if the pspec manifests are out of date, or if a package wasn't bumped or received a greater than +1 release number bump.

Also, FYI I see that @malfisya is bumping VBA-M in getsolus/packages#1381. It may be wise to wait for that to be merged before rebasing just so you only need to do it once.

**Comment by ReillyBrogan** [comment]
getsolus/packages#1381 was merged, so feel free to rebase now. You can hop into our Matrix if you have any issues, we've all done a ton such rebases since it's pretty much what you have to do when you have a monorepo the way we have it.

Also, I'm going to be out all of this week so someone else will be picking this up for reviewing in my stead. Best of luck to you!

**Comment by nelsontkq** [comment]
Rebased! Thanks for the walkthrough. I can definitely see the benefit of splitting out each package in a separate commit now :joy:

**Review by ReillyBrogan — APPROVED** [review]

**Pull request merged**
