### PR TITLE
prusa-slicer: Update to 2.8.0

### PR DESCRIPTION
**Pull request by JacekJagosz**
**Summary**
Update prusa-slicer to 2.8.0
I tried to build it using more system dependencies but this is all I could do. The package wants to cooperate even less than in previous releases.
Changelog:
 - 2.8.0 introduced: Prusa Connect integration, seam improvements, updated UI, new G-code Viewer, improved profile updating system
 - 2.7.0 introduced: SVG emboss, binary G-codes, ramping travels, support for `G2/G3` G-codes, support for Cancel object function
 - a lot of other fixes and improvements

Full release notes:
 - [2.8.0](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.8.0)
 - [2.7.4](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.4)
 - [2.7.3](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.3)
 - [2.7.2](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.2)
 - [2.7.1](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.1)
 - [2.7.0](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.7.0)
 - [2.6.1](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.6.1) 

Fixes [#2628](https://github.com/getsolus/packages/issues/2628) and [#3373](https://github.com/getsolus/packages/issues/3373)

**Test Plan**
Installed latest package from the repository, configured it, imported profiles. Updated to 2.8.0 and checked all the configurations made in all versions stayed. Sliced a file, tested it in gcode viewer. Tested login works to make sure webkit works properly.

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by algent-al** [comment]
It did not build on my machine:

```
[601/604] Linking CXX executable tests/sla_print/sla_print_tests
FAILED: tests/sla_print/sla_print_tests

[602/604] Building CXX object tests/slic3rutils/CMakeFiles/slic3rutils_tests.dir/slic3r_arrangejob_tests.cpp.o
FAILED: tests/slic3rutils/CMakeFiles/slic3rutils_tests.dir/slic3r_arrangejob_tests.cpp.o

[603/604] Building CXX object tests/slic3rutils/CMakeFiles/slic3rutils_tests.dir/slic3rutils_tests_main.cpp.o
FAILED: tests/slic3rutils/CMakeFiles/slic3rutils_tests.dir/slic3rutils_tests_main.cpp.o
```

**Comment by davidjharder** [comment]
It worked for me.

**Review by sheepman4267 — APPROVED** [review]
This builds and runs on my machine as well.

**Comment by davidjharder** [comment]
Successful build! Thanks Jacek

**Pull request merged**
