### PR TITLE
openmw: update to 0.48.0

### PR DESCRIPTION
**Pull request by Staudey**
**Summary**

Highlighted changes:
- Support for post-processing shaders
- Distant object improvements
- Better fog
- Improved rain ripples and particle effects
- Animation refinements
- Overhauled spell and magic effect system
- UI and launcher improvements
- Lua scripting support

Full release notes available [here](https://openmw.org/2023/openmw-0-48-0-released/)

**Test Plan**
- Loaded saved game and played for half an hour
- Tried the new shader system

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by ReillyBrogan — CHANGES_REQUESTED** [review]
Branch needs rebase, I see a `godot` commit in it.

**Comment by Staudey** [comment]
Lol whoops. Will fix when I'm back on Linux.

**Comment by Staudey** [comment]
Done

**Review by ReillyBrogan — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
