### PR TITLE
bolt: update to 0.9.7

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Add a nopcie security level since some devices report nopcie when Thunderbolt
is disabled through BIOS setting.
- Markdown lint styling is used for documents.
- Release notes can be found [here](https://gitlab.freedesktop.org/bolt/bolt/-/blob/master/CHANGELOG.md).

**Test plan**
- Installled and checked that it could see devices.

**Checklist**
- [X] Package was built and tested against unstable.

### CODE REVIEW

**Comment by malfisya** [comment]
Noting that this PR also resolves https://github.com/getsolus/packages/issues/944

**Comment by androidnisse** [comment]
> Noting that this PR also resolves #944

Yes, I totally missed that request. :)

**Review by TraceyC77 — CHANGES_REQUESTED** [review]
The change to the files looks good. Please update the commit message to include a brief summary of the changelog (in this case, 2 lines), per [the docs](https://help.getsol.us/docs/packaging/updating-an-existing-package#package-update). This allows the changelog text to appear in Solus Software Center. Thanks.

**Comment by androidnisse** [comment]
@TraceyC77 Added the summary.

**Comment by TraceyC77** [comment]
Thanks for adding the summary to the commit message. There are a couple of other things I'd like to see.
1 - Please also include the link to the full release notes in the  commit message. See the example in  the docs that I linked. 
2 - The text in this issue should match the commit. You can edit the summary to match.

**Comment by androidnisse** [comment]
@TraceyC77 I think it looks ok now.

**Review by TraceyC77 — APPROVED** [review]
Verified it builds, installs and TB devices are recognized. Looks good. Thanks! 

FYI, when you've addressed review feedback, click the circle icon next to the reviewer's name after you comment. This will notify the reviewer you want them to take another look.

**Pull request merged**
