### PR TITLE
avahi: homepage inclusion

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Added `homepage` key to `package.yml` (Part of #411)

**Test Plan**

- Verified the added homepage loads information about the package

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by algent-al — CHANGES_REQUESTED** [review]
Per GitHub Actions / Checks, builddeps are not in order.

**Comment by malfisya** [comment]
I thought pkgconfig should always listed first, is it not?

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Comment by malfisya** [comment]
`go-task check` have been failing last two days. I should probably file issue later.

**Pull request merged**
