### PR TITLE
llvm: Re-enable PGO and update build configs

### PR DESCRIPTION
**Pull request by ReillyBrogan**
Changes:
- Re-enable building LLVM with PGO
- Enable perf support in the JIT engine
- Build MLIR-C library shared
- Install the lld man page
- Add "Solus $version-$release" to the Clang version
- Disable building libcxx and llvm benchmarks (these weren't installed but were still built previously)
- Ensure that the build-id is always set when writing ELF binaries and that it uses 20-byte output by default
- Use zstd-compressed debug symbols by default for clang/lld/llvm-objcopy (for getsolus/packages#1347)

Addresses the LLVM part of getsolus/packages#1346

### CODE REVIEW

**Comment by ermo** [comment]
@ReillyBrogan: Have you by any chance taken a look at whether it'd be possible to address this? https://github.com/getsolus/packages/issues/1346

**Comment by ReillyBrogan** [comment]
> @ReillyBrogan: Have you by any chance taken a look at whether it'd be possible to address this? #1346

LLVM doesn't use SHA1 for build-ids at all, and hasn't for quite some time. The `Sha1` name is kept mainly for back-compat but always uses BLAKE3 instead but with everything after the first 20 bytes truncated (the length is what is kept for compat with tools that expect 20 bytes of output from `--build-id=sha1`). 

Also LLVM already uses XXH3_64 when you use `--build-id=fast`, not really sure what else there is to do there? My patch only forces build-id=sha1 if `--build-id` is not present or when it is but without a specifier. If you directly use `--build-id=fast` then it will use that.

**Comment by ReillyBrogan** [comment]
I added another patch that compresses debug symbols with zstd by default.

**Comment by ermo** [comment]
> > @ReillyBrogan: Have you by any chance taken a look at whether it'd be possible to address this? #1346
> 
> LLVM doesn't use SHA1 for build-ids at all, and hasn't for quite some time. The `Sha1` name is kept mainly for back-compat but always uses BLAKE3 instead but with everything after the first 20 bytes truncated (the length is what is kept for compat with tools that expect 20 bytes of output from `--build-id=sha1`).
> 
> Also LLVM already uses XXH3_64 when you use `--build-id=fast`, not really sure what else there is to do there? My patch only forces build-id=sha1 if `--build-id` is not present or when it is but without a specifier. If you directly use `--build-id=fast` then it will use that.

The point is more to update _our_ GCC and LLVM defaults to always use (the equivalent to) `--build-id=fast` I think?

If you know from experience that this is a _Bad Idea™_, then we should probably close the related issue...

**Comment by ReillyBrogan** [comment]
Updating this from discussions on Matrix:
- 64bits is a bit on the small side for the default hashing algorithm
- It's unlikely that XXH3 is so much faster than BLAKE3 that it's worth going from 160 bits to 64

**Pull request merged**
