### PR TITLE
minetest: Update to 5.9.1

### PR DESCRIPTION
**Pull request by davidjharder**
**Summary**

- [5.9.1](https://dev.minetest.net/Changelog#5.9.0_.E2.86.92_5.9.1)
- [5.9.0](https://dev.minetest.net/Changelog#5.8.0_.E2.86.92_5.9.0)

**Test Plan**

- Punch trees, get wood

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by algent-al** [comment]
I see same changelog link for 5.9.0 and 5.9.1. I think only one link should be fine here.

**Comment by nauta-turbidus** [comment]
> I see same changelog link for 5.9.0 and 5.9.1. I think only one link should be fine here.

The link for 5.9.0 is wrong, the correct link is this: https://dev.minetest.net/Changelog#5.8.0_.E2.86.92_5.9.0

**Comment by davidjharder** [comment]
Link fixed, thanks

**Comment by nauta-turbidus** [comment]
> Link fixed, thanks

Still wrong link in the commit description.

**Comment by davidjharder** [comment]
try npw

**Comment by nauta-turbidus** [comment]
LGTM

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
