### PR TITLE
hexchat: remove #solus channel recommendation

### PR DESCRIPTION
**Pull request by androidnisse**
**Summary**
- Remove #solus channel recommendations
- Part of https://github.com/getsolus/packages/issues/4297

**Test Plan**
- Installed, checked that #solus was not the default channel.

**Checklist**

- [X] Package was built and tested against unstable

### CODE REVIEW

**Review by davidjharder — COMMENTED** [review]
Might as well add monitoring.

**Comment by androidnisse** [comment]
> Might as well add monitoring.

Still needed even though the repo is archvied?

**Comment by davidjharder** [comment]
Oh, never mind then.

**Review by davidjharder — APPROVED** [review]
LGTM!

**Pull request merged**
