### PR TITLE
labwc: initial inclusion at 0.7.0

### PR DESCRIPTION
**Pull request by Facundo-c-c**
**Summary**

Inclusion of labwc

(second PR, first one delete accidentally for rename branch)

**Test Plan**

Its was installed, and [configure](https://discuss.getsol.us/assets/files/2024-03-01/1709263831-686679-20240301-00h29m25s-grim.png) for daily use.

**Checklist**

- [x] Package was built and tested against unstable

Resolves https://github.com/getsolus/packages/issues/171

### CODE REVIEW

**Comment by davidjharder** [comment]
Hi Facundo, thank you for the PR! 
A few things need to be fixed:
- Please squash your commits so that you have just one commit.
- Please change the commit message from "initial commit" to "labwc: initial inclusion at 0.7.0"
- Please sort the builddeps in the order suggested by the warning. To see the warning, switch to the "files changed" tab and scroll down to package.yml

Also the Package request (https://github.com/getsolus/packages/issues/171) was not actually "Approved" yet, but I just approved it :).

**Review by davidjharder — CHANGES_REQUESTED** [review]
see earlier comment

**Comment by Facundo-c-c** [comment]
trying to squash commits i send one without correct builddeps sort and the warning is gone 😅 , sorry i'm learning how to use git

**Comment by Facundo-c-c** [comment]
> without correct builddeps sort

i found the order of builddeps on the documentation, i think its fixed now

**Review by davidjharder — APPROVED** [review]
Looks good to me. Welcome to Solus packaging!

**Pull request merged**
