### PR TITLE
shortwave: Initial commit to replace gradio

### PR DESCRIPTION
**Pull request by davidjharder**
Resolves https://github.com/getsolus/packages/issues/1456

### CODE REVIEW

**Review by TraceyC77 — CHANGES_REQUESTED** [review]
Shortwave installs and works OK for me on Plasma and Budgie. On Plasma, however, it is missing the "play" icon.
shortwave_20240306_152721

**Comment by davidjharder** [comment]
They look identical here (one of them is in a budgie vm), we need a tie-breaker
Screenshot_20240310_210156

**Comment by HarveyDevel** [comment]
Screenshot_20240311_134532

**Review by TraceyC77 — APPROVED** [review]
Looks good. There's apparently a problem with the GTK theme stuff on my system. Sorry for the delay.

**Pull request merged**
