### PR TITLE
nvtop: Initial inclusion

### PR DESCRIPTION
**Pull request by malfisya**
**Summary**

- Initial inclusion of nvtop
- Resolves https://github.com/getsolus/packages/issues/1335

**Test Plan**

- Open `nvtop` and run `glxgears`
- Make sure activity is shown on `nvtop` (Tested on AMD RX550)

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Review by algent-al — APPROVED** [review]
LGTM, thanks!

**Comment by algent-al** [comment]
Hi @malfisya I landed this, but there is something that still need to be checked. `nvtop` have a desktop file and an icon, but still it isn't available in the Menu.

**Comment by malfisya** [comment]
Really? It showed up on gnome. Will check on others.

**Comment by EbonJaeger** [comment]
@algent-al it's likely a terminal program, and those are currently filtered out of the Budgie menu. I think.

**Pull request merged**
